### ISSUE TITLE
[Documentation Request] System Requirements

### ISSUE THREAD

**Issue by the-solipsist** [mjl-/mox#10]
One reason I'd like to shift from Mailcow is the very heavy system requirements (6GB RAM recommended), especially given `rspamd` and other such resource-intensive components of Mailcow.

It'd be useful to have information on minimum and recommended system requirements.

**Comment by mjl-** [comment]
I am running my email on the smallest VPS my hosting provider has: 1x 70% intel xeon 2.7ghz core, 1gb ram, 60gb disk.
I am the only email user of the system.

I have 229k messages, total disk usage is 5.7gb. The message index is 780mb and the junk filter 100mb. So about 15% storage overhead compared to message size.

CPU load is constantly at zero. These are the current memory stats that top shows:

```
MiB Mem :    976.6 total,    295.3 free,    142.9 used,    538.4 buff/cache
MiB Swap:   1023.0 total,    958.3 free,     64.7 used.    656.9 avail Mem
```

I would suggest you start with as small a machine as you can get, and grow when needed.
There are probably a few places in the code that could be triggered to use more memory, I consider those bugs.

Thanks for asking this, I'm going to add a FAQ!

**Comment by mjl-** [comment]
thanks again, closing this now. feel free to reopen if there is more to discuss, or if you want to share your experience with resource usage!
