### ISSUE TITLE
Unreceived genuine emails due to extra space after MAIL FROM:

### ISSUE THREAD

**Issue by Fell** [mjl-/mox#101]
I have not received an email about a flight schedule change due to this:
```
bad syntax: expected "<" (remaining " <no-reply@koreanair.com>")
```
Now, I know this issue has come up before, but in different ways.

As @mjl- mentioned in https://github.com/mjl-/mox/issues/51#issuecomment-1656138445 the extra space after `MAIL FROM:` is not permitted in SMTP.

> Mox doesn't allow it, as it is normally a sign of spammers with a sloppy SMTP implementation.

However, it appears that airlines, often infamous for their outdated IT infrastructre, also use sloppy SMTP implementations. This is a problem. If I didn't also receive an SMS notifiaction, I would have never known about this schedule change.

I fully understand that Mox wants to only use correct SMTP and prevent as much spam as possible, but I think the implementation needs to be less strict here.

Note: If you want to poke (or blame) the SMTP server in question, it was `tc03.koreanair.com` or `211.218.145.102`.
Edit: Doesn't look like there is an actual SMTP server behind that address.

**Comment by mjl-** [comment]
Hi Fell, thanks for raising this. It's indeed bad if this issue causes mail not to be delivered, I'm afraid sloppy SMTP implementations will be a fact of life...
I'll make the change to accept the additional space soon.

**Comment by Fell** [comment]
I can confirm that epicgames.com is also guilty of the extra space, which is especially problematic because I can't receive their 2FA emails. 

I'm installing from source to confirm the fix now.

**Comment by Fell** [comment]
Can confirm: After installing from the latest commit, previously unreceived emails are now received. 👍🏻
