### ISSUE TITLE
Temporary Return-Path check

### ISSUE THREAD

**Issue by Halyul** [mjl-/mox#103]
Hi, recently I have encountered an issue where the email is being rejected due to the presence of `Return-Path` in the email.

I'm using Zitadel which sends out email with `Return-Path` in the headers ([their code](https://github.com/zitadel/zitadel/blob/fe1337536f9d7e055e53850b060e9ee806b6c1cb/internal/notification/messages/email.go#L42)). 

I noticed that mox [rejects emails](https://github.com/mjl-/mox/blob/e048d0962ba654f2ec02d80cf52c923553954ca7/smtpserver/server.go#L1819) when `Return-Path` is presented. I'm wondering if mox can provide an option to disable this check.

I know complying with RFC is a good practise, but getting it resolved on Ziadel side is much harder. Nevertheless, thanks for your hardwork!

**Comment by mjl-** [comment]
hi halyul, thanks for the report.
Indeed mox is being too strict and not very helpful here. I've changed the check so it only triggers in "pedantic mode".

**Comment by Halyul** [comment]
Thanks for your fast response! Looking forward to the new version!
