### ISSUE TITLE
possible bug in astring() in imapclient/protocol.go

### ISSUE THREAD

**Issue by pexarkh** [mjl-/mox#11]
in this line https://github.com/mjl-/mox/blob/main/imapclient/protocol.go#L151 `stringx` is called but in this line https://github.com/mjl-/mox/blob/main/imapclient/protocol.go#L154 the unquoted incoming string is returned as is.

i've bumped into this issue when trying to login with a password that contained a `{` - the password ended up being sent unquoted and the server responded with `BAD atom contains forbidden char: {`

**Comment by pexarkh** [comment]
i've tested a fix in the playground: https://go.dev/play/p/kw88IwxsxIN

**Comment by mjl-** [comment]
i think that had a missing return of the quoted string. similar to your fix. could check if this makes it work?

and just a note: the imapclient sometimes expects certain responses that a compliant imap client should not necessarily require. imapclient was written to test the imapserver. good to keep in mind, depending on what you're using this for. (:

**Comment by pexarkh** [comment]
i was actually going to adopt it as my primary imap client :) but after spending a quality time with its code, i don't think it was written for such lofty endeavors :) your client's API is just more convenient, particularly in testing, as opposed to the emersion imap client where i have to do things with channels just to fetch messages, like this

```go
    seq, _ := imap.ParseSeqSet("2")
    done := make(chan error, 1)
    messages := make(chan *imap.Message, 10)
    go func() {
      done <- imapClient.UidFetch(seq, []imap.FetchItem{"BODY[TEXT]"}, messages)
    }()
    err = <-done
    assert.NoError(s.T(), err)
    for msg := range messages {
      s.T().Logf("%+v", msg)
    }
```

well, i guess i'm back to emersion now... or python :)

your client is much more intuitive for those who've used python where simple things can be done simply, e.g.

```python
imap.fetch('1', '(BODY[TEXT])')

imap.uid('fetch', '2', '(BODYSTRUCTURE)')

imap.search(None, 'SINCE', '27-Aug-2019')
```

which can be approximated with `Commandf`. so i'm sure quite a few people would appreciate your client emerging from its cacoon of a testing harness into becoming a butterfly of imap :)

**Comment by pexarkh** [comment]
your fix (adding the return statement) works as expected.

fyi, this is a test i used to test it:

```go
import (
  "strings"
  "testing"
)

func Test_astring(t *testing.T) {
  tests := []struct {
    name string
    s    string
    want string
  }{
    {
      name: "empty string",
      s:    "",
      want: `""`,
    },
    {
      name: "no need to escape",
      s:    "blah",
      want: "blah",
    },
    {
      name: "needs to be escaped",
      s:    `blah " { * blah`,
      want: `"blah \" { * blah"`,
    },
    {
      name: "syncliteral with escapees",
      s:    `blah " { * blah` + "\r\n",
      want: tocrlf(`{17}
blah " { * blah
`),
    },
    {
      name: "plain syncliteral",
      s:    `blahblah` + "\r\n",
      want: tocrlf(`{10}
blahblah
`),
    },
  }
  for _, tt := range tests {
    t.Run(tt.name, func(t *testing.T) {
      if got := astring(tt.s); got != tt.want {
        t.Errorf("astring() = %v, want %v", got, tt.want)
      }
    })
  }
}

func tocrlf(s string) string {
  return strings.ReplaceAll(s, "\n", "\r\n")
}

```

**Comment by mjl-** [comment]
Ah yes, that API isn't as simple as one would hope. It's probably because you can have multiple IMAP commands in in progress at a time, and this is to coordinate the responses. The imapclient in mox doesn't do that. Perhaps someone has already written a wrapper for the emersion library that just does one command at a time?

It would be nice to get the imapclient in mox to be more production-read. Would require adding some function, adding a fair bit of test code (it currently has none), and ideally better cross-referencing with the RFCs. I put it somewhere near the bottom of my todo list. Let me know if you would like to work on it.

Thanks for reporting and testing! I'll close the ticket, but feel free to open it up again.
