### ISSUE TITLE
bug in quickstart?

### ISSUE THREAD

**Issue by jsaponara** [mjl-/mox#111]
Output of: "./mox quickstart me@mydomain.com" for mox v0.0.8 binary contained instructions but then switched without warning to config:

...
Configuration files have been written to config/mox.conf and
config/domains.conf. You should review them. Then create the DNS records below.
You can also skip creating the DNS records and start mox immediately. The admin
interface can show these same records, and has a page to check they have been
configured correctly.

; Time To Live of 5 minutes, may be recognized if importing as a zone file.
; Once your setup is working, you may want to increase the TTL.
$TTL 300

; DANE: These records indicate that a remote mail server trying to deliver email
...

**Comment by mjl-** [comment]
"switch without warning to config" is the DNS records right? The lines starting with ";".

Those are in DNS zone file syntax. And the line "Then create the DNS records below" is supposed to introduce them. But The two sentences afterwards continue with prose. Perhaps it's clearer if that paragraph ends with something like: "Add the following DNS records to your DNS zone file, or add them through your DNS operator web interface: "?

Or perhaps I'm misunderstanding the issue.

**Comment by jsaponara** [comment]
Yes that's exactly the issue, thanks, I didn't recognize the format, so the clarification you propose would have helped.

**Comment by mjl-** [comment]
Excellent, thanks for reporting. I'm closing the issue. Feel free to reopen if needed.
