### ISSUE TITLE
setting junk threshold due to smtp rcpt to and message to/cc address mismatch

### ISSUE THREAD

**Issue by p-rintz** [mjl-/mox#118]
Hello,

Im using Mox as my inbox, while having Simplelogin (https://simplelogin.io) in front to handle my domains and aliases.
This forwards all my emails to my Mox inbox.

Due to this , the rcpt to and message to are expected to not match, but this seemingly leads to quite a few emails being bounced.

Is it possible to disable this check? (or even better to whitelist specific domains?)

Thank you.

**Comment by mjl-** [comment]
Given your remark about mismatching "rcpt to" and "message to", I think you're triggering this case:

https://www.xmox.nl/xr/v0.0.9/#smtpserver/analyze.go:410,rfc

The solution should be to mark messages from simplelogin.io as being forwards. See https://www.xmox.nl/config/#cfg-domains-conf-Accounts-x-Destinations-x-Rulesets-dash (this can be changed via the accounts web interface, for an outdated screenshot, see https://www.xmox.nl/screenshots/#hdr-address). Set `SMTPMailFromRegexp` and/or `VerifiedDomain` (SPF match can probably be done, and perhaps they add a DKIM-Signature header) to match the messages. Also set `IsForward`.

Keep in mind that forwarding setups like this have an impact on junk filtering. Simplelogin should now be doing most of the filtering, but it won't have access to your junk/nonjunk classifications...

Hope this helps!

**Comment by p-rintz** [comment]
Perfect, thank you.

Junk filtering isnt really needed in this setup. Thats most of the reason why I use simplelogin. If mail addresses get spam, they get disabled. 

Thanks!
