### ISSUE TITLE
Using self-signed certificate with macOS client, browser reports TLS error after period of time

### ISSUE THREAD

**Issue by haraldrudell** [mjl-/mox#130]
Using self-signed certificates and clicking through unsafe connect in the client browser

After 24 hours connection fails and mox log has:

`Feb 15 04:48:48 c68z mox[2639743]: l=info m="https error" err="http: TLS handshake error from 192.168.1.21:60218: remote error: tls: unknown certificate" pkg=http pkg=net/http`

reloading the page resumes normal operation

— is there something that can be fixed
— or is this unavoidable due to macOS rejection of certificates not in browser certificate store?

**Comment by mjl-** [comment]
I suspect this means the macos client only remembers the "continue unsafely" choice for 24 hours.
You mention you can reload the page. Does that prompt again for accepting the self-signed cert? And which browser is this?

The error message contains "remote error: tls: unknown certificate". That means the remote is sending a TLS alert to us that they don't recognize our cert as valid.

**Comment by mjl-** [comment]
Closing issue, the previous analysis seems likely, and mox can't do anything about it. Feel free to reopen the issue if new info comes to light.
