### ISSUE TITLE
Webmail archive/trash on reply

### ISSUE THREAD

**Issue by mattfbacon** [mjl-/mox#135]
It would be nice to have an option to automatically archive/trash the replied email when you reply to it.

**Comment by mjl-** [comment]
Interesting.

Would that be a setting that you enable? Such as: "Automatically move messages that have been replied to to mailbox: " [select mailbox]. Or just give options for the designed Archive or Trash mailbox.

Of would it be a button next to "Send", like "Send and archive" and/or "Send and trash"

Should it apply to just the message, or the entire thread (if there are more)?

Do you know if/how other mail clients implement this? I don't remember seeing it, but I don't often go looking for settings to change in software (nowadays).

Thought: In theory, this could be implemented on the server side. If the "answered" flag is added, the server could move the message (or thread) to Archive/Trash. I don't think this is a good idea to implement.

**Comment by mattfbacon** [comment]
This is how it's done in gmail: https://www.lifewire.com/send-a-reply-and-archive-with-one-click-in-gmail-1172119

And it's a send option in fairemail: 
![A checkbox in the send options says "Archive replied message"](https://github.com/mjl-/mox/assets/58113890/d02542d8-d07b-4034-98cb-e3b8dfabaad1)

**Comment by mjl-** [comment]
Seems useful, will probably implement this when the settings mechanism/screen is added. It can also be good to have a shortcut like ctrl+shift+enter to archive/trash after sending (where normally ctrl+enter is just sending).

**Comment by mjl-** [comment]
Should be implemented with latest commit. Closing issue, feel free to reopen if more is to be done.
