### ISSUE TITLE
Config option to disable "greylisting" / first time sender slow down

### ISSUE THREAD

**Issue by kbrgmn** [mjl-/mox#144]
Hello, is it somehow possible to disable the "greylisting" / slowing down of SMTP transactions of first-time senders for 15 seconds?

**Comment by mjl-** [comment]
I happened to implement this last week! See https://github.com/mjl-/mox/commit/8b2c97808d8875a817e4de0eab66ffd9ed408201. The config option will be "NoFirstTimeSenderDelay: true" in an Account in domains.conf. Example:

```
Accounts:
	gopher:
		Destinations:
			gopher@gopherwatch.org: nil
		NoFirstTimeSenderDelay: true
```

See https://www.xmox.nl/b/#8b2c97808d8875a817e4de0eab66ffd9ed408201 for running this version. Should be safe to run, no risky commits have happened between v0.0.10 and this commit.

Curious: why would you need this? I implemented it for faster automated processing of incoming email (signup emails). I'm working on more changes in that area.

**Comment by mjl-** [comment]
hi @kbrgmn, i'm closing this issue, since i think it is solved. but feel free to reopen if the suggested solution doesn't work or there are other questions.
