### ISSUE TITLE
How to migrate it onto other server?

### ISSUE THREAD

**Issue by ally9335** [mjl-/mox#166]
Is migrating onto a different server the same as upgrading? https://www.xmox.nl/faq/#hdr-how-do-i-upgrade-my-mox-installation

Backup a) config and b) data directory 

and then, on a different server, restore the data?

**Comment by mjl-** [comment]
Yes indeed.

Don't forget to update your DNS records with the IPs of the new machine (e.g. SPF, MX, MTA-STS), and take DNS TTL (time to live) into account. You may want to reduce the TTL before migrating.

**Comment by ally9335** [comment]
Thx
