### ISSUE TITLE
DNS records and domain configuration check gives possibly inaccurate warnings when behind NAT

### ISSUE THREAD

**Issue by naturalethic** [mjl-/mox#17]
The warnings on the DNS record check page assume that the tcp bind address necessarily will match the public IP address.  This isn't the case for my setup.

I've confirmed the server is working normally, and external checks against MX, SPF, etc, all look good.

Providing some way to inform this checker that the public IP is different than the bound IP might be handy.

**Comment by mjl-** [comment]
Thanks for creating the issue. I think the new config option should help. Could you check if this works for your setup?

**Comment by naturalethic** [comment]
Ok, it took me a while to figure out that I needed to install the @HEAD (rather than @latest).  Looks good!

**Comment by mjl-** [comment]
Excellent, thanks for reporting and testing!
