### ISSUE TITLE
Can't add an account via the command line

### ISSUE THREAD

**Issue by naddika** [mjl-/mox#180]
```
# [ ...mox quick start  ...]


$ ./mox config account add a1 a1@<my_real_domain>.email
adding account: bad request: address not available: domain does not exist

$ ./mox config account add a1 a1@my_fake_domain123.com
adding account: bad request: parsing email address: invalid email address: idna: to ascii: idna: disallowed rune U+005F
```

where `<my_real_domain>.email` is my real domain with the  tld `email`. It's not the domain I specified in `quickstart`

**Comment by RobSlgm** [comment]
Just to make sure: What did you do after `mox quickstart` ?

Without something like  `./mox config domain add <my_real_domain.email> postmaster` no domain except the host domain exists. 
Check ./config/domains.conf --> is you email domain configured?

**Comment by RobSlgm** [comment]
@naddika Not to my knowledge. 

The fastest way is with `./mox config account rm acc1` followed by a `rm -r /home/mox/data/accounts/acc1` and re-create account and re-import.

**Comment by mjl-** [comment]
indeed, recreating the account would be the best way. or logging in and removing the messages manually.
it can be worth deduplicating messages on import in the future. for now i've documented that messages aren't deduplicated as a heads up.
