### ISSUE TITLE
Minor issue: Slightly incorrect helptext for Host TLSRPT

### ISSUE THREAD

**Issue by mdavids** [mjl-/mox#182]
This line is generic:
https://github.com/mjl-/mox/blob/ac3596a7d7bf5f5e86b665b1ac06afc5aac9e430/webadmin/admin.go#L1219

But for a Host TLSRPT it could be wrong.

For example; if the host is mx.example.nl is should say:

```
Ensure a DNS TXT record like the following exists:

	_smtp._tls.mx TXT "v=TLSRPTv1; rua=mailto:tls-reports@mx.example.nl"
```

Now it only says `_smtp._tls`

**Comment by mjl-** [comment]
thanks for reporting! i fixed this record, and made a few others absolute too (they should all be absolute now, matching how they're shown on the page with required dns records).

i still want to split up the records into those that cover only the mail host vs only the host... it's on a todo list.

closing this issue, feel free to reopen if there's more to do.
