### ISSUE TITLE
SRV records

### ISSUE THREAD

**Issue by morki** [mjl-/mox#184]
Hello, thank you very much for mox, it is best.
I have trouble setting this DNS records, with my provider, it does not allow dot (.) in the SRV records.
Is there any other way to make it possible, like setting it to something else, other domain?

```
_imap._tcp.XXX.cz.        SRV 0 1 143 .
_pop3._tcp.XXX.cz.        SRV 0 1 110 .
_pop3s._tcp.XXX.cz.       SRV 0 1 995 .
```

**Comment by mjl-** [comment]
If you can't create those records, it's probably better to just leave them out. The single dot is a signal to email clients during automatic account configuration that those ports/services should not be used. The other records (without the dot) is a signal that those ports _should_ be used. So clients should already pick the services for records that do exist. The records with the dot are only slightly better than those records not existing.

**Comment by morki** [comment]
Thank you for quick response, can you please sometimes in future mark those "yellow" instead of "orange/red" in admin dnscheck to mark those "not so problematic"?
