### ISSUE TITLE
"/webmail" won't load emails, keeps "loading...."

### ISSUE THREAD

**Issue by manaus0xff** [mjl-/mox#195]
All works great except webmail
No errors in the console, nor in the logs
It's behing nginx in the reverse-proxy mode, behind https

![image](https://github.com/user-attachments/assets/135e73ea-93d7-4ed8-a927-3e00b0a68e4d)

The admin section works properly
Desktop email client - thunderbird - works well with the same server 

```
$ ./mox version
(devel)
go1.22.2 linux/amd64
```
However, if I remember correctly, it's `v0.0.11`

**Comment by mjl-** [comment]
@manaus0xff could it be nginx is buffering responses? the webmail uses an SSE connection to stream emails and updates. it could be nginx isn't passing along the server sent events immediately. i think the default with nginx reverse proxying is to buffer, "proxy_buffering on".

**Comment by manaus0xff** [comment]
@mjl- yes. I've added `proxy_buffering off;`, and it's worked. Thanks.
