### ISSUE TITLE
How to choose format of displaying emails in /webmail?

### ISSUE THREAD

**Issue by GildedHonour** [mjl-/mox#196]
I haven't found any setting to specify the **default** and **sticky**  format  to display the emails in as they're always in text. 
 
Is it possible? 

---

I've noticied that it's per domain and sticky.

**Comment by mjl-** [comment]
@GildedHonour The stickiness is per unique "From" address. I added a new webmail setting, a checkbox to show HTML by default instead of text. This default setting is applied only when there's no sticky setting for a From-address. Seems useful, and hope it helps.
