### ISSUE TITLE
I do not understand how to enter the admin panel.

### ISSUE THREAD

**Issue by stroyselmash** [mjl-/mox#20]
I do not understand how to enter the admin panel. 
1. Connected to local panel via ssh tunnel:
sudo ssh -L 80:127.0.0.1:80 -N -f -l root xx.xx.xx.xx.xx -p 22
2. I open the address in a browser http://127.0.0.1
3. I enter the issued passwords:
 "Admin password: yyyyyyyyyy 
 IMAP and SMTP submission password for test@test.com: xxxxxxxxxx"
4. Login - test@test.com, password - xxxxxxxxxxxx, everything is ok, I'm in.
But how to get into the admin panel?
Password I see - yyyyyyyyyy, what login and do I go there? Admin;yyyyyyyyy or admin;yyyyyyyyyy or admin@test.com;yyyyyyyyyyy?
Thanks in advance, I know it's a stupid question, but I'm stuck on this))

**Comment by mjl-** [comment]
The admin panel is at http://127.0.0.1/admin/. Thanks for reporting, I'll clarify the the docs! Hope this gets you going again.

**Comment by mjl-** [comment]
I think this last commit will make it clearer for future users. I'll close this issue, please reopen if you there is still a problem. Thanks again!
