### ISSUE TITLE
Old domains continue to remain active for log-in at webmail

### ISSUE THREAD

**Issue by ally9335** [mjl-/mox#203]
Sometimes I won't extend some of my domains. I'll instead buy the same domain but with other TLD.  I've notificed that old, expired, domains will allow me to log in indefinitely. Huh? 

Also, any domain, whether it belongs to me or not, can be added for the purpose of log-in, even microsoft.com. I won't be able to send and receive anything from it. However, I'll be able to use it as a login domain.  Right?

**That's not an issue.**  And in my case it's even better, because I might forget which domain is currently active: domain1.com, domain1.xyz, domain1.space ...  But once I've added domain1.xyz, I'll be able to continue to use it for log-in for years, with multiple other domains under a single account.

**Comment by mjl-** [comment]
Indeed. You can configure any domain in mox, but you won't be able to make the needed DNS settings to make email work if you don't own the domain. Mox isn't checking if a domain is configured correctly before allowing login with an address. Not when initially configuring it, or later when a domain is no longer configured.

It's not yet possible to disable some addresses for an account. There is another issue to disable some addresses of an account.

**Comment by mjl-** [comment]
I don't think there's anything to change about mox for this issue, right? Closing this, but feel free to reopen if there's work to be done.
