### ISSUE TITLE
Webmail rarely does not parse From header

### ISSUE THREAD

**Issue by morki** [mjl-/mox#204]
Hi @mjl-,

I am happy user of mox for some time, but today I saw something that seems like a bug.

I recieved email from my wife from her work address, and in webmail (I don't use any other client) I see no From header.

![image](https://github.com/user-attachments/assets/6f79a8da-3c60-4a8b-81c0-34cdbf2db430)

But when I open email source, I see encoded From header.

![image](https://github.com/user-attachments/assets/df75bfac-e06f-4563-a1f3-75786be13015)

Maybe there is a bug in parsing? Maybe the new line in between is not standard?

It was sent by Exchange 365 server from Outlook in Windows.

I can privately share you the source email, it was just a request for print of some application document.

**Comment by morki** [comment]
Thank you very much for so quick fix @mjl-, I can confirm it works now like a charm.

For others maybe visiting this, you should run `mox reparse` command to reparse the messages for changes to take effect.

**Comment by mjl-** [comment]
Great! And good point about running `mox reparse`, I'll mention it in the release notes. I'll try to get a release out in the next week, it's been quite some time.
