### ISSUE TITLE
remove unnecessary characters from 2024b/d._domainkey records

### ISSUE THREAD

**Issue by GildedHonour** [mjl-/mox#209]
web > admin/dnsrecords

Why not make the  `2024b._domainkey, 2024d._domainkey` 

records a single, long string which could be copied-pasted as is? Rather than the ones with quotes, new lines and whitespaces which are had to be removed before insertion

**Comment by mjl-** [comment]
@GildedHonour The record is currently on multiple lines to make it a valid line in zone files. The integration tests use the same records (also generated by the quickstart) in a configuration file used by unbound. It would reject the rsa dkim record for being too long (dns strings can be max 255 bytes). Other software, mostly dns operator web interfaces only accept single long strings. This has come up before, and I plan to make an interactive web-based quickstart to make it easier to properly configure dns records, but it will take a while before I get to it. We'll still need this admin web page showing records.

How about we just _also_ show the rsa dkim record as a single string, but commented out. The integration tests won't pick it up, but users can copy-paste it just as easily into a dns operator web interface.

**Comment by GildedHonour** [comment]
@mjl yes
