### ISSUE TITLE
Internal alias delivery seems not to work

### ISSUE THREAD

**Issue by wneessen** [mjl-/mox#220]
Hi again,

I am currently testing the alias feature. I've set up an alias "wn@" for my actual account "winni@". Sending mails from external works fine, but if I try to send a mail from my "winni@" address to the "wn@" address and I seend it, the server accepts the mail but it's not delivered to my mailbox. I see the sent mail in my "Sent" folder, but mail itself is not delivered to my inbox.

Am I doing something wrong?

**Comment by mjl-** [comment]
If I understand the situation correctly, you have an address "winni@", and an alias "wn@" that expands to (among others?) "winni@", and sending a message from "winni@" to "wn@" doesn't deliver the message to "winni@". That seems "intended", see the comment at this alias configuration key: https://www.xmox.nl/config/#cfg-domains-conf-Domains-x-Aliases-x-Addresses: "If the address in the message From header is a member, that member also won't receive the message.". I think the idea was to prevent getting duplicate messages in your thread. But I can see why this is unexpected (or leaves doubt as to whether the sending or alias works properly). Perhaps it should be an option in the alias to also deliver to members that sent the message.

**Comment by wneessen** [comment]
Ah, got it. I set up the the alias in the admin UI so I didn't even see that config comment. It was just confused that no mail was delivered, while the initial mail was in the "Sent" folder. But I see the point of reducing duplicates. I like the idea of making it configurable, but maybe just making the information more visible in the adminUI would be sufficient already.

In any case my question is answered. Thanks!

**Comment by mjl-** [comment]
> maybe just making the information more visible in the adminUI would be sufficient already

yes, good one, let's start with that. we can let this issue open until at least that is addressed.

**Comment by mjl-** [comment]
The commit should make it less likely to confuse users.
We may still add an option to disable the "not send to address in message From header" behaviour. But it's probably best to wait for someone to want it.

**Comment by mjl-** [comment]
Part of v0.0.12, so closing the issue. Feel free to reopen if problems persist.
