### ISSUE TITLE
Account deletion not deleting local files - causing backup warning

### ISSUE THREAD

**Issue by wneessen** [mjl-/mox#221]
Hi again,

I've just tried the backup functionality and got this output:

```
warning: backing up unrecognized file; path=accounts/toni.tester/index.db
warning: backing up unrecognized file; path=accounts/toni.tester/junkfilter.bloom
warning: backing up unrecognized file; path=accounts/toni.tester/junkfilter.db
warning: backing up unrecognized file; path=accounts/toni.tester/msg/a/1
warning: backing up unrecognized file; path=accounts/toni.tester/msg/a/3
warning: backing up unrecognized file; path=accounts/toni.tester/msg/a/4
warning: backing up unrecognized file; path=accounts/toni.tester/msg/a/5
```

`toni.tester` was a test account I had setup during the initial testing phase and later deleted via the admin UI. Apparently the local files of the account were not deleted but only the entry in the config files. Now the backup process is seeing the local files but cannot associate them (I think).

Is it safe to delete the whole directory manually?

**Comment by mjl-** [comment]
> Is it safe to delete the whole directory manually?

Yes, you can safely remove it.
This has been addressed in https://github.com/mjl-/mox/commit/30ac690c8f64558487a26bc6797c9cb7ac034d7d, but it hasn't made it into a release yet...

**Comment by wneessen** [comment]
Thanks!
