### ISSUE TITLE
how to chat? mox not found on matrix.org

### ISSUE THREAD

**Issue by startup-001-steve** [mjl-/mox#226]
Hi, 
I would like to chat, to ask questions about the capability of spam filtering, and configuring "rules" for per domain and per user.

I could not find the chat room using element web, in matrix.org
Is there a direct link?

![14 10 2024_13 59 57_REC](https://github.com/user-attachments/assets/c2d9d126-6d7b-462a-8d31-b1b89a6cb218)

**Comment by mjl-** [comment]
Here is a direct link: https://matrix.to/#/#mox:matrix.org

In some clients, #mox:matrix.org may be enough. I think that's the full "address".

I tried clicking the "publish as public room" for the room, but the Elements web app is giving me a generic error that it failed. Hope you can find it.

**Comment by mjl-** [comment]
Excellent, committed with minor change, thanks!
