### ISSUE TITLE
Cannot change postmaster reporting address

### ISSUE THREAD

**Issue by exander77** [mjl-/mox#228]
I cannot seem to change reporting addresses like:
```
dmarc-reports
tls-reports
```

**Comment by mjl-** [comment]
You should be able to configure that per domain through the DMARC and TLSRPT "Localpart" field. See https://www.xmox.nl/config/#cfg-domains-conf-Domains-x-DMARC-Localpart and https://www.xmox.nl/config/#cfg-domains-conf-Domains-x-TLSRPT-Localpart.

Or through the web interface. The screenshots on the mox website don't show it, but here's a screenshot (when in the page about the domain).
![mox-reporting-addresses](https://github.com/user-attachments/assets/c656ac27-b2e5-4a2c-87f2-644798658b3d)

Make sure to update DNS records after changing these addresses!

**Comment by exander77** [comment]
I most likely misformulated it, the address itself was the issue, but the account that address leads. But I know understand, that I can change it in mox config file.

**Comment by mjl-** [comment]
Good to hear, thanks for the feedback. Closing the issue for now, feel free to reopen if there's still a change to be made in mox.
