### ISSUE TITLE
"Send and archive thread" when already in archive (#135 followup)

### ISSUE THREAD

**Issue by mattfbacon** [mjl-/mox#233]
Followup to #135, when the replied-to email is already in the Archive, we should either remove the button or at least not give an error about already in destination mailbox.

**Comment by mjl-** [comment]
@mattfbacon Thanks for reporting. I think the commit above fixes the problem for the largest part. The commit message details.

For a binary with the latest commit, see https://www.xmox.nl/b/#879477a01f72fa9202bef8acc652ec8970da1bc7.

**Comment by mattfbacon** [comment]
Yes it works thanks.
When updating I noticed that the behavior of the web handlers changed. They were returning 404 and I had to add mail.<domain> to the web handlers config to fix it (the actual hostname of the server is vps2.<domain> because I have multiple). Is this documented?

**Comment by mjl-** [comment]
@mattfbacon v0.0.12 changed the web routing a bit. There was this in the
release notes that was supposed to cover it:

> Improve http request handling for internal services (web interfaces) and
> multiple domains. The handler for /admin/ is now only enabled on the listener
> (machine) host name by default, no longer all hosted domains. The internal
> handlers (for admin, account, webmail, webapi), can now also be explicitly
> configured in the webserver section, for additional/custom endpoints to serve
> those services on. (https://github.com/mjl-/mox/issues/160 by TragicLifeHu, https://github.com/mjl-/mox/commit/614576e409a6e2f115bc6c11bd03a50b9b45ddec)

But there was no further call to action in the "update instructions". I
should have mentioned it there, for the case of different domains/hostnames
the web interfaces were used on...

**Comment by mattfbacon** [comment]
No worries, it is still 0.x so expected. Thanks
