### ISSUE TITLE
Duplicate header fields listed in generated DKIM-Signatures

### ISSUE THREAD

**Issue by snabb** [mjl-/mox#234]
This is with mox-v0.0.12-go1.23.2.

I observed that some header fields are listed twice in `DKIM-Signature` headers' `h=` tags that mox generates: `From`, `To`, `Subject`, `Date`, `Message-Id` and `Content-Type` are listed twice. I believe this is a bug.

I have not altered the DKIM headers configuration (it is unspecified in `domains.conf` i.e. it is using just the defaults). The duplicates are not displayed when looking at the DKIM section of the domain configuration via admin web UI (at `/admin/#domains/XXX.com`). 

See below for example (with PII redacted with XXX):
```
DKIM-Signature: v=1; d=XXX.com; s=2024a; i=XXX@XXX.com;
	a=ed25519-sha256; t=1729698265; x=1729957465; h=From:To:Cc:Bcc:Reply-To:
	References:In-Reply-To:Subject:Date:Message-Id:Content-Type:From:To:Subject:
	Date:Message-Id:Content-Type;
	bh=3Zqy53hycaa5kdT5Za6XqiFwsn+LGl4VbkUi1EoPZIU=; b=ntFN3vrGFlCiA4aBY+O+KESinB
	4VHaTuVNT+uivVpDG9fOfnm4+BqGTl7robz6mRwHsbSAST0DlQNsRioQqQDg==
DKIM-Signature: v=1; d=XXX.com; s=2024b; i=XXX@XXX.com; a=rsa-sha256;
	t=1729698265; x=1729957465; h=From:To:Cc:Bcc:Reply-To:References:In-Reply-To:
	Subject:Date:Message-Id:Content-Type:From:To:Subject:Date:Message-Id:
	Content-Type; bh=3Zqy53hycaa5kdT5Za6XqiFwsn+LGl4VbkUi1EoPZIU=; b=UJAMcuaMytaY
	s9S3VUeyRIXDnIuO3aKuvT9k+Fymlfep5vF0uSWCcqsNG0+sWMl7NcQxguav76HogO3UBCMf8j6bg
	iX7XATb69lo8GTwhj68guxVTZmwFKYJ7ojH2NYllpwsbN1A7rGTZGVh8I9pJBF+TcBRZ/XqnuPjNW
	oBH1WHapYF9VuK9AA0c6ToMk2Bc98Z6jDYyGcbdv1hLrDsEEGoV869pamoi/VY90qq7oxpoPVsP/T
	fiYuvTi8b5/aK6sdVluI7hq52xMf22ZZ898VdKwcITz+2SsG/hRSsW3p0IwPYRibD9FsfbLSVSa5F
	FDwrcv5GLs1j1ToUVt04hA==
```

RFC 6376 states the following:
> The field MAY contain multiple instances of a header field name, meaning multiple occurrences of the corresponding header field are included in the header hash.

So this would be correct behavior if the relevant e-mail had multiple occurrences of those fields... but the e-mail contains only single instance of those fields, so the emitted `DKIM-Signature` syntax is thus not correct with those duplicates. I wonder if they are included once or twice in the hash input...

**Comment by mjl-** [comment]
The duplicate header names are for "sealing" or "oversigning" the header names. The RFC may not mention it by that name, but it is a commonly used concept in DKIM. Mox enables it by default on DKIM keys. If you want to disable it, set https://www.xmox.nl/config/#cfg-domains-conf-Domains-x-DKIM-Selectors-x-DontSealHeaders.

Consider a message that passes the DKIM verification check, with header name "X" signed. By sealing, a copy of the message with another header for "X" added will not pass the DKIM verification check. Without sealing it would. Different software interpreting a message may interpret the headers differently: Some may use the first, others may use the last value for "X". Beside confusion, it could lead to security issues.

**Comment by snabb** [comment]
Right. That makes sense. Didn't know about this. Thanks and sorry for the noise!

PS. Very refreshing to work with mox after coming from old-school Exim+Dovecot+etc. world!

**Comment by mjl-** [comment]
No worries, happy to help, and good to hear!
