### ISSUE TITLE
SRV 0 0 0 .

### ISSUE THREAD

**Issue by bwbroersma** [mjl-/mox#240]
Currently the `0 1 port .` is used:
https://github.com/mjl-/mox/blob/68c130f60e3ac8b6004b8dd2ef7d4a3bdc968116/mox-/admin.go#L936-L943

Instead of `0 0 0 .`, like in the RFC examples of [RFC 2782](https://datatracker.ietf.org/doc/html/rfc2782#:~:text=SRV%20%200%200%200%20%2e) or [RFC 6186](https://datatracker.ietf.org/doc/html/rfc6186#:~:text=SRV%20%200%200%200%20%20%20%2e).

Is there any reason to include the port number and pick a weight of `1`?
Note [this RFC 2782 quote](https://datatracker.ietf.org/doc/html/rfc2782#:~:text=order%2eb-,Domain,noisy%29%2e) about the weight selection:
> Domain administrators SHOULD use Weight 0 when there isn't any server selection to do, to make the RR easier to read for humans (less noisy).

BTW cool you already implemented these records, I was researching it for:
- https://github.com/internetstandards/Internet.nl/issues/1538

**Comment by mjl-** [comment]
Excellent, thanks! I don't think I had a reason for not using weight 0. I wouldn't be surprised if I never looked at RFC 2782...
