### ISSUE TITLE
[Feature] Support WebSocket upgrade protocol in reverse proxy.

### ISSUE THREAD

**Issue by naturalethic** [mjl-/mox#25]
I'm trying to install a service (minio) as proxied by mox, and some features do not work because a web socket connection cannot be established.

**Comment by mjl-** [comment]
Sounds reasonable to want. It looks like websockets shouldn't be too hard to implement, though will have to keep an eye on potential security issues. I presume in this case that minio is offering a ws:// url? Or is it wss://? Let me know if you have  know about things the implementation would need take special care for.

I don't know when I'll have time to work on this. I'm short on time at the moment.

**Comment by mjl-** [comment]
i'll try to look at the PR tomorrow, thanks for sending it in!

**Comment by mjl-** [comment]
i had a look, and i'm afraid we'll need a different approach.
see https://github.com/golang/go/issues/18152 for comments on the golang.org/x/net/websocket package. summary: it is providing the wrong api (without knowing the details, it looks it isn't preserving the payload type).
the suggested implementation with gorilla also isn't great: gorilla is deprecated. besides that, i don't want to introduce external dependencies this easily.
and i think we don't have to. i think we can get away with only monitoring the websocket "handshake", passing it along to the backend, verify that the backend understands it, and forwards its response. and then just shuffle around the bytes both sides send each other. that does mean the backend is exposed to potentially invalid websocket frames. we could in theory monitor the frames too, but i don't think it's worth the trouble. the whole point of websocket is to communicate mostly raw bytes between two sides (http just happens to be in the way).
i'll try to get this concept working in a basic form and will report back.

**Comment by mjl-** [comment]
this latest commits made my basic websocket application work (built with golang.org/x/net/websocket) when forwarded through mox.

@naturalethic when you are ready for it, you could give it a try.

@154pinkchairs with this approach, only the http request/response part of websockets are verified/interpreted by mox. if that looks good, meaning the backend has the right headers indicating support, the connection is upgraded and mox just copies data between the client and the backend. golang.org/x/net/websocket is indeed useful for testing! but in the PR you made, i think we ended up parsing the websocket framing, and packing it again when copying. i think we would lose information when interpreting the frames. could you have a look at the last commit? i don't normally use websockets, so i may not be up to date on all the intricacies and have missed some handling.

**Comment by mjl-** [comment]
great to hear, thanks for testing, and thanks @154pinkchairs for the PR!
