### ISSUE TITLE
New setup failure

### ISSUE THREAD

**Issue by mocallins** [mjl-/mox#254]
Just following the instructions.

```
mox@webserver:~ $ ./mox quickstart -existing-webserver admin@****.com
Checking if DNS resolvers are DNSSEC-verifying...
checking dnssec support in resolver: lookup com. on 68.105.28.12:53: dial udp 68.105.28.12:53: i/o timeout
mox@webserver:~ $```

I've gone and checked my domain setup and it appears that i have DNSSEC enabled.

**Comment by mjl-** [comment]
Hi @mocallins!

The mox quickstart does a lookup for NS records of .com, to see if DNSSEC is configured in the resolver. It seems the nameservers you have configured don't respond to that request, resulting in the timeout. At first glance, I suspect there's something strange going on with 68.105.28.12. Perhaps it shouldn't be used as dns server, or the response message is too large and changing to dns over tcp doesn't work properly.

Could you check that 68.105.28.12 is in /etc/resolv.conf and that that's correct? And that it responds to other DNS queries.

Could you run `dig ns com. @68.105.28.12`?  If that sticks to UDP and doesn't result in a timeout, we'll have to figure how dig does dns differently than mox.
Trying `dig +tcp ns com. @68.105.28.12` should tell if dns over tcp works properly.

You can also run `mox -loglevel debug dns lookup ns com.` to test how mox is making dns requests. The quickstart uses the same code, so I expect it will result in a timeout too.

Seeing the dig output can help with further debugging.

**Comment by mocallins** [comment]
Ok here's some into.

```
[webserver]:</home/pi/> cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 68.105.28.11
nameserver 68.105.29.11
nameserver 68.105.28.12
```

```
[webserver]:</home/pi/> ping google.com
pinging google.com
PING google.com (142.250.113.113) 56(84) bytes of data.
64 bytes from rs-in-f113.1e100.net (142.250.113.113): icmp_seq=1 ttl=59 time=32.9 ms
64 bytes from rs-in-f113.1e100.net (142.250.113.113): icmp_seq=2 ttl=59 time=16.6 ms
64 bytes from rs-in-f113.1e100.net (142.250.113.113): icmp_seq=3 ttl=59 time=14.8 ms
64 bytes from rs-in-f113.1e100.net (142.250.113.113): icmp_seq=4 ttl=59 time=17.2 ms
64 bytes from 142.250.113.113: icmp_seq=5 ttl=59 time=17.5 ms

--- google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 20154ms
rtt min/avg/max/mdev = 14.788/19.774/32.862/6.609 ms
```

```
[webserver]:</home/pi/> nslookup google.com
Server:         68.105.28.11
Address:        68.105.28.11#53

Non-authoritative answer:
Name:   google.com
Address: 142.250.114.139
Name:   google.com
Address: 142.250.114.102
Name:   google.com
Address: 142.250.114.100
Name:   google.com
Address: 142.250.114.138
Name:   google.com
Address: 142.250.114.113
Name:   google.com
Address: 142.250.114.101
Name:   google.com
Address: 2607:f8b0:4023:1002::65
Name:   google.com
Address: 2607:f8b0:4023:1002::66
Name:   google.com
Address: 2607:f8b0:4023:1002::8b
Name:   google.com
Address: 2607:f8b0:4023:1002::71
```


```
[webserver]:</home/pi/> dig ns com. @68.105.28.12
;; communications error to 68.105.28.12#53: timed out
;; communications error to 68.105.28.12#53: timed out
```

This popped back immediatley.
```
C[webserver]:</home/pi/> dig +tcp ns com. @68.105.28.12

; <<>> DiG 9.18.28-1~deb12u2-Raspbian <<>> +tcp ns com. @68.105.28.12
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2518
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;com.                           IN      NS

;; ANSWER SECTION:
com.                    172800  IN      NS      c.gtld-servers.net.
com.                    172800  IN      NS      d.gtld-servers.net.
```

```
mox@webserver:~ $ ./mox -loglevel debug dns lookup ns com.
debug: dns lookup result: lookup com. on 68.105.28.12:53: read udp 192.168.0.220:57197->68.105.28.12:53: i/o timeout; pkg=dns; type=ns; name=com.; resp=[]; authentic=false; duration=30.025060008s
dns lookup: lookup com. on 68.105.28.12:53: read udp 192.168.0.220:57197->68.105.28.12:53: i/o timeout (without dnssec)
```

**Comment by mocallins** [comment]
```
mox@webserver:~ $ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 1.1.1.1
nameserver 8.8.8.8
mox@webserver:~ $ ./mox quickstart -existing-webserver admin@collinsinfotech.com
Checking if DNS resolvers are DNSSEC-verifying...
checking dnssec support in resolver: lookup com. on 8.8.8.8:53: dial udp 8.8.8.8:53: i/o timeout
```

**Comment by mjl-** [comment]
Perhaps your ISP is filtering some DNS traffic? And perhaps they don't want you to contact other DNS servers?

Did you do more of the digging and is that leading to any insights?

A possible direction could be to look into DNS over TLS and DNS over HTTPS. They were partly invented to sidestep issues with ISPs doing funny things with DNS.

**Comment by mjl-** [comment]
I would enabling logging on unbound and see what that says. It can show its incoming requests, what it is doing to handle them, and any errors it encounters along the way. I can imagine it is seeing some connectivity issues.

Have you tried these DNS lookups on a different machine on the same network? And doing them on a machine in a different network. It can help to understand which part of the failures are due to the machine or due to the network.

**Comment by mjl-** [comment]
Could you see if https://cmdns.dev.dns-oarc.net/ shows any issues? It should test your DNS resolving situation.
If you cannot load that site on the machine that is seeing the problems, you could use the cli version of the tool, https://github.com/DNS-OARC/cmdns-cli. Can be installed with `go install github.com/DNS-OARC/cmdns-cli@main` (not `@latest` which their docs show). Or get a binary from https://beta.gobuilds.org/github.com/DNS-OARC/cmdns-cli@v1.1.1-0.20241018080647-90b281ce9117/linux-arm64-go1.23.3-stripped/0r6q1pLKdC7NapqNT96Y-vbIbyWM/.
The tool prints lots of JSON output. Best run it as `cmdns-cli -done >dns.txt` followed by a "grep complete dns.txt", which should show results of the tests. The rest of dns.txt could then be helpful in finding details about issues found.

**Comment by mocallins** [comment]
Hmmm, well those 68.105.*.*  dns entires are from my isp 'COX' and have been used for the past 5 years, no problems really.

Any / all machines that i use with dhcp get those addresses, including my windows workstation, and i rarely have any DNS problems, unless i go goofing around with something, like in the past with Pi-hole and Unbound, which never worked out at all.

Now i'm trying again because MOX has some issue, that i have no conrtol over, or very little to say the least, short  of gettting Unbound to work, which isn't yet.

That was a nice tool to try, i have no idea what its telling me

**Comment by mocallins** [comment]
Well, go figure, lol

```
To access these from your browser, run
"ssh -L 8080:localhost:80 you@yourmachine" locally and open
http://localhost:8080/[...].

If you run into problem, have questions/feedback or found a bug, please let us
know. Mox needs your help!

Enjoy!
```

i found a much simpler setup for Unbound and only had to tweak 2 lines i think, lol

```
    forward-addr: 8.8.8.8@853#dns.google.com
    forward-addr: 1.1.1.1@853
```

I just guessed at the @853, from the example i had, lol

**Comment by mocallins** [comment]
Ok, now going through  the output, updating/creating all the DNS records.

Not quite sure about the TLS cert files from:
```
mox@webserver:~ $ ./mox config test
tls config for "listener public": parsing x509 key pair: reading tls certificate: open config/path/to/webserver.collinsinfotech.com-chain.crt.pem: no such file or directory
```

**Comment by mjl-** [comment]
Do you have certbot or another ACME tool set up? It will put its certificates somewhere, eg /etc/letsencrypt/live/.... You can point to those and you would have to configure a hook to restart mox when a new certificate has been fetched by the acme tool.

Without -existing-webserver, mox will do ACME on its own, for all certificates needed. That's why I normally recommend that approach.

Keep in mind you will need at least a certificate for the (MX) hostname. And for each domain, `autoconfig.<domain>` if autoconfig is enabled, and `mta-sts.<domain>` is mta-sts is enabled.

If you want to use DANE (needs DNSSEC setup for your own domain), you have to make sure the ACME tool you're using doesn't create new private keys each time it requests a new certificate (because the corresponding public key in the DANE TLSA records are used for TLS verification by clients delivering email to you). A more advanced/elaborate alternative is using an ACME tool that automatically updates the DNS TLSA records.

**Comment by mocallins** [comment]
Hmmm,  well i secured my site with an add-on to Apache, and i forgot what its called, but it does get it from LetsEncrypt

**Comment by mocallins** [comment]
i think it may be mod_md, which apparently is ACME for Apache, lol

**Comment by mocallins** [comment]
I think i found the path to my website certs / keys.

But i don't know anything about  _mta-sts_ and _autoconfig_

**Comment by mjl-** [comment]
mta-sts is and autoconfig are both optional.
mta-sts helps to secure delivery of email to your system.
autoconfig helps email clients find the correct server settings when you setup a new account.

**Comment by mocallins** [comment]
Yep, commented those out since i didn't know what to use.

I'm using CloudFlare for my DNS and they have an option on their site to setup the mta-sts policy file.
Would i need to run the certbot step ?

Also getting the config to finally complete with ok.
Got it to run as a service, its all looking ok, so i tried the web interface and getting this for admin login:
```
Error: login: cannot find ip for rate limit check (missing x-forwarded-for header?)
```

**Comment by mocallins** [comment]
LOL  Ok, i figured it out, options in the mox.conf file
I'll go ahead and close this and them open new for anything else.
I imagine setup is complete, since i cas access the admin web interface.
Thanks for the help

**Comment by mjl-** [comment]
> I'm using CloudFlare for my DNS and they have an option on their site to setup the mta-sts policy file.
> Would i need to run the certbot step ?

For mta-sts, no special certbot handling is needed (regardless of doing it in
mox or at cloudflare)

I would normally configure mta-sts in mox itself. Especially with ACME setup
that's the easiest option. But when manually configuring certificates, it
means adding another one per domain.

> Error: login: cannot find ip for rate limit check (missing x-forwarded-for header?)

You probably figure it out. But this happened due to the reverse proxy not
setting x-forwarded-for headers, which mox expects with the
"-existing-webserver" option.
