### ISSUE TITLE
Found  NATIPs conf option, but don't think its taking effect.

### ISSUE THREAD

**Issue by mocallins** [mjl-/mox#259]
Running mox in a homelab environment, natted.
Is this correct in the email details, trail ?

```
<html>
<body>
<!--StartFragment-->
10mins 6s ago | 90517ms |   |   |   | dialing smtp server: dial tcp 192.168.0.220:0->67.195.204.77:25: i/o timeout
-- | -- | -- | -- | -- | --


<!--EndFragment-->
</body>
</html>
```

Seems like it should be the public facing ip address ?

**Comment by mjl-** [comment]
The NATIPs option only tells mox that it is running in a NAT configuration, and what the actual external IPs are. Mox uses those IPs for its self-checks. It does not influence how outgoing smtp connections are made. So the IPs in the dial error message look reasonable. It's not great that you're seeing a timeout... Hope that doesn't happen for all outgoing connections.

What were you expecting the NATIPs config option to do?

**Comment by mocallins** [comment]
> The NATIPs option only tells mox that it is running in a NAT configuration, and what the actual external IPs are. Mox uses those IPs for its self-checks. It does not influence how outgoing smtp connections are made. So the IPs in the dial error message look reasonable. It's not great that you're seeing a timeout... Hope that doesn't happen for all outgoing connections.


 
> What were you expecting the NATIPs config option to do? 
Just trying to figure out why i cannot get outbound email to work, actually and inbound email as well.

**Comment by mocallins** [comment]
Yea i tried DNS Checker, and another 1 that wants to charge for the info, but neither seemed to be of much help.
The free on did provide
```
Reverse DNS does not match SMTP Banner.
```
But i couldn't find any further info , on what that means, or how to repair

My ISP is Cox, and i've never seem to got much help from them. To tell you the truth i don't think their very smart about any of this.
They just want you to use what you pay for as run of the mill, and not have to help at all.

**Comment by mocallins** [comment]
Would this cause a problem ?

`
IP: 68.12.151.20

Hostname: ip68-12-151-20.ok.ok.cox.net.
`

Even though i'm trying to claim it on my dns ?

**Comment by mjl-** [comment]
Could you give some more details of the error messages you are seeing? There's not enough to go on now.
Is it incoming _and_ outgoing email that isn't working?
It will help to see logging from mox. You can enable trace logging to get all the protocol details.

FWIW, I cannot connect to 68.12.151.20 on port 25. You may be able to connect from inside your network, but from outside it appears blocked.

**Comment by mocallins** [comment]
Yes neither incoming nor outgoing email is occurring.

I will be happy to provide whatever logs you need, just point me in the right direction.

Also here's what i see from telnet to the smtp port.

```
helo collinsinfotech.com
250-webserver.collinsinfotech.com
250-PIPELINING
250-SIZE 104857600
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-LIMITS RCPTMAX=1000
250 SMTPUTF8
```

Don't know it helps.


I guess nevermind. it looks as if my isp is actively blocking port 25

Is there anyway of changing the port , although i wouldn't know how the outside world would know to use a different port   :(

**Comment by jujoparo** [comment]
Dear sir.
Thank you very much for your help.

Is It possible to use a public dynamic IP behind Nat? Is it possible to specify a Fqdn in the IPs settings like this:

IPs: mail server.domain.com, 192.168.1.1
NATIPs: 192.168.1.1

What would it happen if after the server starts the pubt IP changes? Would it be necessary to restart the mail sever?
