### ISSUE TITLE
Unexpected EOF error message when using IMAP with an iPhone

### ISSUE THREAD

**Issue by ArnoSen** [mjl-/mox#39]
Hi, 

I just configured my mail powered by Mox on my iPhone. Initially I had some issues. I found out that I needed to specify the IMAPS port in the incoming mailserver. Also in the Advanced Settings, I had to tick the 'Use SSL' option. After that, mail was coming in.

 They are however some 'unexpected EOF error messages in the log. See the logs below. Maybe it is an client issue but maybe not so just sharing with you what I am experiencing:

Jun 13 22:24:02 mail mox[442]: l=info m="new connection" pkg=imapserver remote=84.241.202.251:31796 local=46.19.33.172:993 tls=true listener=public cid=188b1503298 delta="26.966µs"
Jun 13 22:24:02 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=authenticate duration=39.519169ms cid=188b1503298 delta=175.422065ms username=me@mydomain
Jun 13 22:24:02 mail mox[442]: l=info m="client id" pkg=imapserver params="map[name:iPhone Mail os:iOS os-version:16.5 (20F66) version:20F66]" cid=188b1503298 delta=46.736494ms username=me@mydomain
Jun 13 22:24:02 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=id duration="457.512µs" cid=188b1503298 delta="431.192µs" username=me@mydomain
Jun 13 22:24:02 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=list duration="122.654µs" cid=188b1503298 delta=39.431873ms username=me@mydomain
Jun 13 22:24:02 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=list duration=1.225618ms cid=188b1503298 delta=38.943354ms username=me@mydomain
Jun 13 22:24:02 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=list duration="531.21µs" cid=188b1503298 delta=311.639876ms username=me@mydomain
Jun 13 22:24:17 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=noop duration="116.384µs" cid=188b1503298 delta=14.469507125s username=me@mydomain
Jun 13 22:24:17 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=select duration="350.692µs" cid=188b1503298 delta=48.239783ms username=me@mydomain
Jun 13 22:24:17 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd="uid search" duration="639.469µs" cid=188b1503298 delta=64.666156ms username=me@mydomain
Jun 13 22:24:17 mail mox[442]: l=info m="imap command ioerror" err="unexpected EOF (fatal io error)" pkg=imapserver cmd= duration=47.791878ms cid=188b1503298 delta=47.177274ms username=me@mydomain
Jun 13 22:24:17 mail mox[442]: l=info m="connection closed" err="unexpected EOF (fatal io error)" pkg=imapserver cid=188b1503298 delta="253.692µs" username=me@mydomain

**Comment by ArnoSen** [comment]
Maybe I know what it is.... give me a day or what to see the error is gone... I will let you know or close the issue myself.

**Comment by mjl-** [comment]
> I found out that I needed to specify the IMAPS port in the incoming mailserver. Also in the Advanced Settings, I had to tick the 'Use SSL' option. After that, mail was coming in.

as far as I know, this is a problem with ios mail. ios mail doesn't appear to do any autoconfiguration (at least not one of the public and common ones, though it appears apple has an internal database with account settings for big providers, but i haven't been able to find any information on that). it does try to guess settings, but it guesses settings that are unlikely to work with modern mail servers. it would be great to make it less error-prone to set up an email account in ios mail. i think the best solution is to find a way to get ios mail to automatically find the correct settings.

i have another issue with connection. ios mail often shows connection errors after a period of inactivity. it could be that the tcp keepalive is getting in the way somehow. i still have to investigate that. but it looks different from what you are seeing.

have you found a reason for the disconnects/closed connections you were seeing?

**Comment by ArnoSen** [comment]
I checked some more occurences of EOF. 
It looks like it is an indication that the remote side ended the connection.
See below two other log traces where EOF errors show up.

Maybe this is not a big deal. On the other hand when reading the logs you tend to think that something went really wrong while maybe this is not the case.

```
Jun 15 18:18:07 mail mox[442]: l=info m="new connection" pkg=smtpserver remote=104.248.251.39:54514 local=46.19.33.172:25 submission=false tls=false listener=public cid=188b1503493 delta="65.486µs"
Jun 15 18:18:07 mail mox[442]: l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=help code=214 ecode=2.0.0 duration="14.504µs" cid=188b1503493 delta="421.436µs"
Jun 15 18:18:08 mail mox[442]: l=info m="connection closed" err="read: EOF (fatal io error)" pkg=smtpserver cid=188b1503493 delta=1.519997861s
```


```
Jun 15 14:17:23 mail mox[442]: l=info m="new connection" pkg=imapserver remote=83.80.152.96:58106 local=46.19.33.172:993 tls=true listener=public cid=188b1503475 delta="103.12µs"
(..)
Jun 15 14:30:07 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=idle duration=6m36.441692883s cid=188b1503475 delta=5m44.260209448s username=me@mydomain
Jun 15 14:30:07 mail mox[442]: l=debug m="updating junk filter" pkg=imapserver untrain=false untrainjunk=false train=true trainjunk=false cid=188b1503475 delta=23.745481ms username=me@mydomain
Jun 15 14:30:07 mail mox[442]: l=debug m="inserting words in junkfilter db" pkg=imapserver words=10 cid=188b1503475 delta=8.122528ms username=me@mydomain
Jun 15 14:30:07 mail mox[442]: l=debug m="broadcast changes" pkg=imapserver changes="[mailboxid=2 uid=16]" cid=188b1503475 delta=8.833008ms username=me@mydomain
Jun 15 14:30:07 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=append duration=24.90865ms cid=188b1503475 delta="436.348µs" username=me@mydomain
Jun 15 14:30:07 mail mox[442]: l=debug m="imap command done" pkg=imapserver cmd=noop duration="69.679µs" cid=188b1503475 delta=9.428978ms username=me@mydomain
Jun 15 14:30:07 mail mox[442]: l=info m="imap command ioerror" err="unexpected EOF (fatal io error)" pkg=imapserver cmd= duration=42.665861ms cid=188b1503475 delta=42.60306ms username=me@mydomain
Jun 15 14:30:07 mail mox[442]: l=info m="connection closed" err="unexpected EOF (fatal io error)" pkg=imapserver cid=188b1503475 delta="551.628µs" username=me@mydomain
```

**Comment by mjl-** [comment]
I hope the commit makes the errors look a bit less bad and that the EOFs were indeed just clients closing the connection. Feel free to reopen again if there's something left to fix.
