### ISSUE TITLE
Setting admin and accounts password headless

### ISSUE THREAD

**Issue by pmarini** [mjl-/mox#42]
I'm building a template for mox using the LXD-based framework of Nextcloud-related templates as available here: https://codeberg/pmarini/nc-env

As part of the provisioning I'm trying to pass the admin and an account password from the command line:

Example:

```
$ echo admin 321 | ./mox setaccountpassword admin@mox-mail-server.localenv.com
```
fails.

Is there a flag or another shell technique that allows to pipe the password in `setaccountpassword` and `setadminpassword`?

**Comment by mjl-** [comment]
Could it be you are running setaccountpassword before starting mox? It will try to talk to a running mox instance.
"mox setadminpassword" just writes a file, so that can't be the problem there. Which error messages are you seeing? Setting a password like in your example seems to work for me.

**Comment by pmarini** [comment]
Hello,

setadminpassword is working as expected. My bad, it was indeed a file permission issue.

Didn't have time yet to test setaccountpassword, but this is a little bit less relevant.

**Comment by pmarini** [comment]
Ok for me, thanks!
