### ISSUE TITLE
Unable to login as admin

### ISSUE THREAD

**Issue by FieryCod** [mjl-/mox#43]
Empty username and password doesn't work. How can I debug it and provide more info?

**Comment by mjl-** [comment]
hi @FieryCod! an empty username is correct, but your password should not be empty. the initial password was printed during the quickstart. you can also set a new password by running "mox setadminpassword" (mox doesn't have to be running).

if you are already sending the non-empty admin password, the next step would be to look at the logging output. the default log level is "debug", which prints access logging for all http requests. the request to the admin endpoint should be something like:

```
debug: "http request" (cid: 188f4180a72; pkg: http; httpaccess: ; handler: admin; method: get; url: /admin/; host: localhost:1080; duration: "254.544µs"; statuscode: 200; proto: http/1.1; remoteaddr: 127.0.0.1:53364; tlsinfo: plain; useragent: "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0"; referrr: ; size: 79061)
```

the important part is `handler: admin`. if the handler isn't admin, the request isn't getting to the admin endpoint. it could be that you're trying to access the /admin/ page on the "public" listener. the quickstart only enables it on the "internal" listener by default, with internal ip's. i.e. this in config/mox.conf:

```
Listeners:
        internal:
                IPs:
                        - 127.0.0.1
                        - [...]
                AdminHTTP:
                        Enabled: true
```

at startup, mox prints the listeners and handlers that it sets up. there should be a line like this:

```
l=print m="http listener" pkg=http name=local kinds="admin-http at /admin/" address=127.0.0.1:1080
```

so the admin endpoint is at http://127.0.0.1:1080/admin/.

if this also isn't the problem, it would help if you could send the "http request" logging output. it will probably give me a hint for where to look next. a little bit of additional logging in `func checkAdminAuth` in http/admin.go would probably show what's going on.

hope this helps!

**Comment by lemos1235** [comment]
I also failed. The page shows http 401 - unauthorized - mox account - login with email address and password. After checking the log, I found that it was judged as`account ` handler, not `admin`.

**Comment by mjl-** [comment]
Ah, interesting, are you saying that you were opening http://localhost/admin/ and ended up at the account handler? And was this a default quickstart config?

**Comment by lemos1235** [comment]
I serve the mail server on remote machine, and I test it using ssh forward, so the url is http://localhost:8080/admin

**Comment by lemos1235** [comment]
I got it, I lost the / at the end. so that should be `http://localhost:8080/admin/`, not `http://localhost:8080/admin`

**Comment by mjl-** [comment]
Good info, thanks! I'll look into adding a redirect from /admin to /admin/ because I think more people will run into this at some point.

**Comment by mjl-** [comment]
I hope the previous commit solved it. Closing the issue, but feel free to reopen if there is more to do.
