### ISSUE TITLE
Interpreting warning in dnscheck / IPrev

### ISSUE THREAD

**Issue by pmarini** [mjl-/mox#59]
Not sure how to interpret the outcome of the IPRev test:

```
# IPRev
error: Reverse name(s) mail01.lxd for ip 10.246.192.25 do not match hostname mail.mydomain.com, which will cause other mail servers to reject incoming messages from this IP.

```
Mox is running in an LXD container so it is expected that the internal DNS reports the `.lxd` part. This can be changed but I'm not sure whether it makes sense as this is not the public address of the container. The reverse DNS of the public address of the host server is correctly set.

Is this warning worrying? Does it make sense to have the test run also on the private ip?

**Comment by mjl-** [comment]
Indeed it doesn't really help anything to change the DNS for .lxd.
Mox assumes the IPs of the public listener are public IPs. If they are not, you can specify the public IP in the public listener under NATIPs, I believe this option was added in the previous release. That should make the IPRev check work against the public IP listed in NATIPs.
Let me know if that doesn't work.

Does mox have that specific IP in its config file under the public listener? Or do you have the unspecificed address "0.0.0.0" there? If the specific private IP, I think mox should at least recognize that during the quickstart and set up NATIPs by itself.

Thanks for the report!

**Comment by pmarini** [comment]
Thanks for the quick reply!:

I added NATIPs with the public address and the warning went away.

> Does mox have that specific IP in its config file under the public listener? Or do you have the unspecificed address "0.0.0.0" there? If the specific private IP, I think mox should at least recognize that during the quickstart and set up NATIPs by itself.

Specific private IP here, no "0.0.0.0".

**Comment by mjl-** [comment]
On 2023-09-07 17:11, pmarini wrote:
> Specific private IP here, no "0.0.0.0".

Good to know, thanks. I think mox can still detect this case during quickstart and add the NATIPs. Will try adding it soon. We could leave this issue 
open until it is completed.

**Comment by mjl-** [comment]
I hope the commit above would prevent issues for future quickstart users. I did some local testing, but if you're in the position to easily verify, that never hurts! Thanks for reporting!

**Comment by pmarini** [comment]
I'm not used to and don't have a go build system in my test environment. Is there a build that includes this commit? If not, I'll try as soon as it is released in a new version.

**Comment by mjl-** [comment]
> I'm not used to and don't have a go build system in my test environment. Is there a build that includes this commit? If not, I'll try as soon as it is released in a new version.

Here is a link to a build with the latest commit (it is a pre-v0.0.7 version):

***@***.***/linux-amd64-go1.21.1-stripped/06TZkxYKzJSW-VMixylKsAZxdo20/

I hope to get the release out of the door this weekend.

**Comment by mjl-** [comment]
Interestint. Let's try that through the web form: https://beta.gobuilds.org/github.com/mjl-/mox@v0.0.7-0.20230922135305-a0f3856e4005/linux-amd64-go1.21.1-stripped/06TZkxYKzJSW-VMixylKsAZxdo20/

**Comment by pmarini** [comment]
I did a `mox quickstart` and verified that `NATIPs` entries are written in the `Listeners.public` section.

Is this enough to validate the fix?

**Comment by mjl-** [comment]
Sorry for the late reply, I did see your comment come in at the time. Yes, that validated it, thanks!
Closing the issue, feel free to reopen if needed.
