### ISSUE TITLE
Logging to a file

### ISSUE THREAD

**Issue by lormayna** [mjl-/mox#6]
Is there a way to log to a file?
This would be perfect to couple with fail2ban to block spammers and bots.

**Comment by mjl-** [comment]
No, not by mox itself. If you want to log to a file, you could redirect the output to a file yourself. Luckily I never had the need for fail2ban or 
similar tools. Don't they support reading logs from the common logging destinations?

By the way, mox has some builtin options for ratelimiting. E.g. too many auth failures cause new connections to be rejected (smtp/imap), and so do a 
high connection rate or too many concurrent connections (from ip or subnets).

**Comment by belst** [comment]
if you use systemd (journald), you can set `backend = systemd` in your fail2bans jail config

**Comment by mjl-** [comment]
Thanks belst, sounds like a good approach. I'll consider this resolved.
