### ISSUE TITLE
Interpreting warning in dnscheck / MX

### ISSUE THREAD

**Issue by pmarini** [mjl-/mox#60]
Not sure why I get the following warning when I do dnscheck command:

```
None of the IPs that mx "mail.s.mydomain.com." points to is ours: [nnn.mmm.nnn.mmm]

Ensure a DNS MX record like the following exists:

	mydomain.com. MX 10 mail.s.mydomain.com.

Without the trailing dot, the name would be interpreted as relative to the domain.
```

This is the MX entry in my DNS:

```
mydomain.com.		IN	MX	10 mail.s.mydomain.com.
```
I also have an A record:

```
mail.s		IN	A	nnn.mmm.nnn.mmm
```

Did I do anything wrong? My DNS management is hosted at Hetzner
Thanks

**Comment by mjl-** [comment]
I think this may be caused by the private-IP in public Listener in the config file.
If you would add your public IP under NATIPs in the public listener, I think this warning will go away.
If you already have that IP in NATIPs, we'll have to dig deeper!

**Comment by pmarini** [comment]
Yes, the NATIPs config, as mentioned in #59, solved the issue. Thanks

**Comment by mjl-** [comment]
I think this is solved, feel free to reopen if needed.
