### ISSUE TITLE
Webmail: login issue when downloading attachments

### ISSUE THREAD

**Issue by x8x** [mjl-/mox#62]
When downloading a message attachment , the login prompt pop up again, not an error but annoying.

**Comment by mjl-** [comment]
I did some testing just now, and am seeing this behaviour with Safari. It asks to remember to allow downloads, so hopefully you wouldn't have allow it each time. It's specifically about the downloading, the same attachment will be displayed inline without login popup. Are you seeing this with a different browser than Safari? Always good to understand the situation fully.

I suspect we'll solve this with a non-HTTP-basic-authentication login, also see issue #58.

**Comment by x8x** [comment]
Yes, Safari here and no, I am using a password manager and don't want Safari itself to remember it.

As you noted this is temporary and will not be an issue once we get the non-HTTP-basic-authentication login.

And it is much appreciated to have Webmail ASAP and not having to wait for that feature to be implemented!
So, not complaining at all, just noting the behaviour.
