### ISSUE TITLE
Rejects folder: should messages be set as unread?

### ISSUE THREAD

**Issue by x8x** [mjl-/mox#63]
Messages in the `Rejects` folder show up as `read` shouldn't they be marked as `unread`?
The annoyance is when moving them to `Inbox` they should logically display as `unread`.

**Comment by mjl-** [comment]
They are added to the Rejects as "read" so they don't constantly draw attention. I would be inclined to look at the messages in the rejects folder too often. It is a good idea to mark messages that are moved out of the Rejects mailbox as unread.

Having messages in the Rejects mailbox should hopefully be very rare. It is for me. So let's investigate (in issue #64) why that is happening.

**Comment by x8x** [comment]
> They are added to the Rejects as "read" so they don't constantly draw attention.

Absolutely, marking them as "read" in the Rejects folder to avoid constant alerts is a smart feature.
Your commit that toggles them to "unread" only when moved is truly ingenious!
