### ISSUE TITLE
macOS's Mail.app bad apple!

### ISSUE THREAD

**Issue by x8x** [mjl-/mox#65]
For some unknown reason, since ever, macOS's Mail.app email client has been a PITA when it comes to manually configure self hosted accounts! The experience is to say it politely frustrating, with delays and errors and "randomness", looks like it is trying to do its own intelligent things instead of simply following protocols.

Instead, using Profiles is a no-brainer !

Wondering, now that Mox has Webmail, what about generating a `.mobileconfig` Profile and sending it as attachment upon account creation or modification?
This would make it easier for users to set up they new shiny email account:
- login to webmail
- download attached Profile
- install Profile
- done!

Another option is to have per account web links generated to download such Profiles directly.

Fore reference here is some Go code to generate such Profiles:
https://github.com/ProtonMail/proton-bridge/blob/master/pkg/mobileconfig/template.go

**Comment by mjl-** [comment]
Apple is indeed making it hard for everyone. Even if you manually enter account details they somehow always manage to select non-sane defaults that won't work with reasonable servers...

Your solution sounds like a great idea. A "welcome" message for an account also sounds good in general. Hopefully this helps with iOS mail too. The template looks simple enough.

**Comment by mjl-** [comment]
Loving your feedback by the way. Keep it coming. (:

**Comment by x8x** [comment]
> Hopefully this helps with iOS mail too. The template looks simple enough.
The same profile functions seamlessly on both macOS and iOS. It's worth noting that these profiles can be conveniently generated by users via [Apple Configurator](https://support.apple.com/apple-configurator) if trust concerns arise. If the profile is unsigned, an alert will be displayed during installation. Signing the profile necessitates that the author possesses an Apple Developer account.

**Comment by mjl-** [comment]
I was able to set up macOS mail and iOS mail with the new mobileconfig files. I put links them in the account web interface so they are always available (btw, I plan to merge the account interface into the webmail client at some point). For iOS the qr code was most convenient for me.

I suspect signing these profiles is going to be too troublesome (requiring importing the signing key into mox, and adding code to do signing).

**Comment by x8x** [comment]
Amazing! Thank you!!
