### ISSUE TITLE
Setting password for non-existent account should fail.

### ISSUE THREAD

**Issue by x8x** [mjl-/mox#68]
running `mox setaccountpassword non-existent-user@domain.com` will change the admin password and admin login will be possible with:
user: non-existent-user@domain.com
password: [the just set up password]

**Comment by mjl-** [comment]
> running `mox setaccountpassword ***@***.***` will change the admin password and admin login will be possible with:
> user: ***@***.***
> password: [the just set up password]

Could it be you have a wildcard account for @domain.com?
The setaccountpassword command will try to open by email address, and wildcards will resolve to an account.
The distinction between account name and email address is probably going to cause problems/confusion. Perhaps its better to require that setaccountpassword is passed an account name (which doesn't have to be an email address), especially given the name.

Though the wildcard-theory would still not explain changing of the admin password, i.e. the one you would use to access http://localhost/admin/ to manage domains and accounts.

**Comment by x8x** [comment]
Ouch, bad wording on my side, I was thinking about admin as the owner of the wildcard account I set up for a specific domain. Not to be confused with the mail server admin. Sorry for the confusion!

Indeed, the wildcard account does explain the behavior I mentioned; so, it's not an error per se.
Yes, using the account name instead of one of its email addresses as argument to `setaccountpassword` is probably a better choice.

**Comment by mjl-** [comment]
The commit switches the setaccountpassword subcommand to use an account instead of email address. Should be a saner and safer choice.
