### ISSUE TITLE
Wrong SRV check

### ISSUE THREAD

**Issue by lormayna** [mjl-/mox#7]
I am launching a dnscheck and I am getting this:

# SRVConf
error: Missing SRV record "_submissions_.tcp.test.mydomain.me"
error: Missing SRV record "_submission_.tcp.test.mydomain.me"
error: Missing SRV record "_imaps_.tcp.test.mydomain.me"
error: Missing SRV record "_imap_.tcp.test.mydomain.me"
error: Missing SRV record "_pop3_.tcp.test.mydomain.me"
error: Missing SRV record "_pop3s_.tcp.test.mydomain.me"

According to RFC2782:

> Proto
        The symbolic name of the desired protocol, with an underscore
        (_) prepended to prevent collisions with DNS labels that occur
        in nature.  _TCP and _UDP are at present the most useful values
        for this field, though any name defined by Assigned Numbers or
        locally may be used (as for Service).  The Proto is case
        insensitive.

Then the record must be:
"_submissions._ tcp.test.mydomain.me" instead that "_submissions_.tcp.test.mydomain.me"

**Comment by mjl-** [comment]
Could it be github has modified the underscores in your text? I'm seeing it as if there was a lookup for `_submissions_.tcp.test.mydomain.me`. Mox should be doing lookups for `_submissions._tcp.test.mydomain.me`.

See rfc 6186 for some concrete examples for the email services.

**Comment by mjl-** [comment]
In the mean time I've had a report of an email client that used the SRV records to configure itself. So the SRV records look correct. I'll close the issue. Please reopen if you find a case where a client should support autoconfig with SRV records, but it doesn't work.
