### ISSUE TITLE
Init script and dnscheck questions

### ISSUE THREAD

**Issue by zkazsi** [mjl-/mox#74]
I've very recently discovered mox: I started using it, but discovered a few issues.
Installed using docker compose, using it on owndomain.net, 

### Generated DNS config and errors
- towards end of initial config, I should generate following DNS settings (optional, however checked on admin)

```
_imap._tcp.owndomain.net.         IN SRV 0 1 143 .
_submission._tcp.owndomain.net.   IN SRV 0 1 587 .
```
(I'm not setting pop3 settings, since I don't use that for sure)

Issue is the dot (".") at the end of those lines: this is not a valid setting on my DNS interface. I tried setting also to mail.mydomain.net (since this is the setting for _imaps._tcp and _submission._tcp, 
then when this didn't work also mydomain.net , however this throws errors on the Admin - DNS check interface. 

On checking on the admin page, I get errors:
```
Unexpected SRV record(s) for "_submission_.tcp.owndomain.net"
Unexpected SRV record(s) for "_imap_.tcp.owndomain.net"
```

What would be the correct setting, since "." doesn't work?

### Reverse DNS name mismatch

Another issue, I find strange: where does mox take the reverse dns info from?
On the dnscheck page it shows racknerd-x12345 , however I've changed the reverse DNS name already weeks ago to mail.owndomain.net (on the VPS interface) , and when I check in various tools, it shows correctly as mail.owndomain.net 
This results in following error on dnscheck: 
``` Reverse name(s) racknerd-x12345 for ip 45.xx.1xx.1xx do not match hostname mail.owndomain.net, which will cause other mail servers to reject incoming messages from this IP ```
I've checked reverse dns for example at https://dnschecker.org/reverse-dns.php , https://mxtoolbox.com/ReverseLookup.aspx and https://www.debouncer.com/reverse-dns-check  (and other sites), everywhere showing correctly. 

I'm wondering, where does mox take this info?

(Maybe it's just my obsessivness, I don't want to see errors :) Sending mails works well, also to gmail for example, even showing in Prioritiy Inbox right away)

**Comment by zkazsi** [comment]
Unsure if I should open another issue, but I have another problem (probably user error, but would be thankful for pointers)

### Can't use smtp for sending from external programs (only from Webmail) 

Signing in to mail programs (K-9, or Fairemail on Android and Thunderbird on PC) does not work for sending / smtp. 
Error message in log: 
```l=debug m="smtp command result" err="authentication only allowed on submission ports" pkg=smtpserver kind=smtp cmd=auth code=503 ecode=5.5.1 duration="217.213µs" cid=18b03d7fff9 delta=720.209173ms```
What are "submission ports" here? I'm trying to use either 465 for SSL/TLS or 587 for SMARTTLS

Any idea , what to check specifically?

Right now I can only use mox via webmail for sending mails. 
Using smtp and sending has worked well previously for example from maddy on the same machine, with same settings

Any help will be appreciated

**Comment by mjl-** [comment]
hi zsolt!

> ### Generated DNS config and errors
> - towards end of initial config, I should generate following DNS settings (optional, however checked on admin)
> 
> ```
> _imap._tcp.owndomain.net.         IN SRV 0 1 143 .
> _submission._tcp.owndomain.net.   IN SRV 0 1 587 .
> ```
> Issue is the dot (".") at the end of those lines: this is not a valid setting on my DNS interface.
> 
> On checking on the admin page, I get errors:
> ```
> Unexpected SRV record(s) for "_submission_.tcp.owndomain.net"
> Unexpected SRV record(s) for "_imap_.tcp.owndomain.net"
> ```

The dot in the SRV record indicates that that service/port is not in use. Like with pop3, you can also just leave it out if it is causing trouble. That's better than setting it to your host, because it may cause mail clients to try to use it! Not sure why you would get errors for that. Could it be a missing dot at the end of the host name? That's required.

For reference, the behaviour for the single dot is specified at https://datatracker.ietf.org/doc/html/rfc6186#section-3.4. So seems like a bug in the admin panel. You probably can't fix that, so best to work around it...


> ### Reverse DNS name mismatch
> 
> Another issue, I find strange: where does mox take the reverse dns info from?

Mox also just does a PTR lookup (reverse dns) on the IP it is configured for. It tries to find your actual public IPs. Normally by just looking at the public IPs on the network interfaces. But in a container it may only get IPs in the private range. In that case, it will try to use the IPs of the (guessed) hostname. E.g. mail.yourdowmain.example. But you may have to use the -hostname flag when you are running in a container, because it will otherwise probably guess a wrong hostname, e.g. yourcontainerhostname.yourdomain.example.

Are you seeing this during the quickstart only? Or also in the DNS check page after having set it up? If you are running with only private IPs, have you configured the actual public IPs in the "NATIPs" field in the public listener in config/mox.conf? By setting NATIPs, mox will check only the reverse DNS of those IPs. So if those IPs have correct reverse DNS (sounds like it), the warning/error should go away. If NATIPs is correctly set (or there is no NAT), it would help to see what DNS lookups inside the container return. You could perhaps open a shell in the container and try "host 1.2.3.4" with your IP.

> (Maybe it's just my obsessivness, I don't want to see errors :) Sending mails works well, also to gmail for example, even showing in Prioritiy Inbox right away)

I agree with the approach. Clean up warnings/errors! (:

**Comment by mjl-** [comment]
> ### Can't use smtp for sending from external programs (only from Webmail) 
> 
> Signing in to mail programs (K-9, or Fairemail on Android and Thunderbird on PC) does not work for sending / smtp. 
> Error message in log: 
> ```l=debug m="smtp command result" err="authentication only allowed on submission ports" pkg=smtpserver kind=smtp cmd=auth code=503 ecode=5.5.1 duration="217.213s" cid=18b03d7fff9 delta=720.209173ms```
> What are "submission ports" here? I'm trying to use either 465 for SSL/TLS or 587 for SMARTTLS
> 
> Any idea , what to check specifically?

Could you look for other log lines with cid=18b03d7fff9? The earliest lines should say which IP and port the connection is to. The submission ports are indeed 465 (immediate/implicit TLS) and 587 (STARTTLS), and should allow you to authenticate. I would only expect the error message you're seeing for connections to port 25 (for delivery with SMTP between servers). Some clients (like Apple's) sometimes try to login on port 25, but for me Thunderbird autoconfiguration picks up the correct settings automatically.

So, I think it may help to see a little more logging. You could also enable loglevel trace (perhaps only for package "smtpserver") to capture some login attempts, perhaps something is special about them.

**Comment by zkazsi** [comment]
Hi Mechiel!

I very much appreciate your quick and very helpful answers .

First issue with "." in SRV is solved  - frankly, it was apparently my mistake

> For reference, the behaviour for the single dot is specified at https://datatracker.ietf.org/doc/html/rfc6186#section-3.4. 

Thank you so much for this reference as well.

> ### Reverse DNS name mismatch 
> But you may have to use the -hostname flag when you are running in a container, because it will otherwise probably guess a wrong hostname, e.g. yourcontainerhostname.yourdomain.example. 

Mox apparently sees the correct hostname (mail.owndomain.example) everywhere , it seems only the reverse lookup fails

You mention , tunning it with -hostname flag: I see this however only mentioned for the quickstart: where would I need to add it in the docker-compose file (if you think it would help)?

> Are you seeing this during the quickstart only? Or also in the DNS check page after having set it up? 

I see this error both on Quickstart and also on the DNS check page

> If you are running with only private IPs, have you configured the actual public IPs in the "NATIPs" field in the public listener in config/mox.conf? By setting NATIPs, mox will check only the reverse DNS of those IPs. So if those IPs have correct reverse DNS (sounds like it), the warning/error should go away. 

I haven't set NATIPs previously, but have tried it now: unfortunately the problem remains
So, to be clear, in the config file, under "Listeners" I have these four lines:
```                
IPs:
                        - 45.9z.x.y
NATIPs:
                        - 45.9z.x.y
```

**Comment by zkazsi** [comment]
> ### Can't use smtp for sending from external programs (only from Webmail) Signing in to mail programs (K-9, or Fairemail on Android and Thunderbird on PC) does not work for sending / smtp. 
> Could you look for other log lines with cid=18b03d7fff9? The earliest lines should say which IP and port the connection is to. The submission ports are indeed 465 (immediate/implicit TLS) and 587 (STARTTLS), and should allow you to authenticate. I would only expect the error message you're seeing for connections to port 25 (for delivery with SMTP between servers). ... So, I think it may help to see a little more logging. You could also enable loglevel trace (perhaps only for package "smtpserver") to capture some login attempts, perhaps something is special about them.

I can see my previous log line was not helpful (probably not even related to my IP).
So, with some additional data

```
mox-mail-mox-1  | l=debug m="autotls setting allowed hostnames" pkg=autotls hostnames=[autoconfig.example.com;mail.example.com;mta-sts.example.com] publicips=[45.95.x.y]
mox-mail-mox-1  | l=print m="starting as root, initializing network listeners" pkg=serve version=v0.0.7 pid=1 moxconf=/mox/config/mox.conf domainsconf=/mox/config/domains.conf
mox-mail-mox-1  | l=print m="listening for smtp" pkg=smtpserver listener=public address=45.95.x.y:25 protocol=smtp
mox-mail-mox-1  | l=print m="listening for smtp" pkg=smtpserver listener=public address=45.95.x.y:465 protocol=submissions
mox-mail-mox-1  | l=print m="listening for imap" pkg=imapserver listener=public addr=45.95.x.y:993 protocol=imaps
```

Based on this it would appear to me that mox is listening on port 465, submissions
However, it seems like connections on port 465 from externals never arrive to that port: all the connection requests I can see in the log are on port 25 (from various other IPs), and successful connections to imaps port 993 from my IP

One of the errors with more lines, NOT from my IP:
```
mox-mail-mox-1  | l=info m="new connection" pkg=smtpserver remote=147.78.x.y:53591 local=45.95.x.y:25 submission=false tls=false listener=public cid=18b091ff633 delta="402.474µs"
mox-mail-mox-1  | l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=ehlo code=250 ecode= duration="154.501µs" cid=18b091ff633 delta=21.009349ms
mox-mail-mox-1  | l=debug m="smtp command result" err="authentication only allowed on submission ports" pkg=smtpserver kind=smtp cmd=auth code=503 ecode=5.5.1 duration="278.807µs" cid=18b091ff633 delta=12.406397ms
mox-mail-mox-1  | l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=quit code=221 ecode=2.0.0 duration="34.61µs" cid=18b091ff633 delta=12.383084ms
mox-mail-mox-1  | l=info m="connection closed" pkg=smtpserver cid=18b091ff633 delta="416.962µs"
```

So, as I currently understand: my auth requests for smtp submissions never arrive to the server (for some reason). I also don't see errors from others trying to connect to 465 => it would appear, port is closed : somewhat surprising due to the fact that 25, 587, 993 and others are open

Anyways, as I understand, I have following steps to follow:

- look into the possible port blocking for 465, talk to my provider (racknerd)
- try to reconfigure mox to use port 587. As I understand, by default only using 465 (most secure option), however I see , it should be possible to activate 587 (SMARTTLS) in mox. (I'll go through config and also DNS setttings for this)
- will also try to get more data with trace option, as recommended by you
- and finally, would it be possible, all of this is related to my other issue with reverse DNS mismatch? (possibly, imapserver able to listen on 993, but smtp server not listening on 465???)

Otherwise, everything looks awesome: I get 9.5 score from mail-tester, and my trial mails to gmail arrived even under Priority :) ... all of these sent from webmail, of course

**Comment by zkazsi** [comment]
Quick update on this:

> try to reconfigure mox to use port 587. As I understand, by default only using 465 (most secure option), however I see , it should be possible to activate 587 (SMARTTLS) in mox. (I'll go through config and also DNS setttings for this)

This has worked, I'm able to send from external programs (tested w/Thunderbird)
Of course, still interesting to understand, why port 465 doesn't work ( is it: 1) vps provider blocking, or 2) something in mox)

Now, the only remaining issue is the reverse DNS, even though that's also not blocking usage (at least no negative effects discovered so far)

**Comment by mjl-** [comment]
> You mention , tunning it with -hostname flag: I see this however only mentioned for the quickstart: where would I need to add it in the docker-compose file (if you think it would help)?

It would only be useful during quickstart: It uses the value to write the config/mox.conf config file.

> > Are you seeing this during the quickstart only? Or also in the DNS check page after having set it up? 
> 
> I see this error both on Quickstart and also on the DNS check page

ok, then it's the actual reverse lookup that is giving back these results.

> I haven't set NATIPs previously, but have tried it now: unfortunately the problem remains
> So, to be clear, in the config file, under "Listeners" I have these four lines:
> ```                
> IPs:
>                         - 45.9z.x.y
> NATIPs:
>                         - 45.9z.x.y

If the IPs are the actual public IPs (instead of private IPs, like 10.x.x.x), then the NATIPs shouldn't be used. NATIPs is only in case mox is behind a NAT so mox doesn't see the public IP.

Have you tried getting a shell in the container where mox is running and trying to do a reverse lookup? With commands host, dig or nslookup.

Example:

> $ host 1.1.1.1
> 1.1.1.1.in-addr.arpa domain name pointer one.one.one.one.

**Comment by mjl-** [comment]
> This has worked, I'm able to send from external programs (tested w/Thunderbird)
> Of course, still interesting to understand, why port 465 doesn't work ( is it: 1) vps provider blocking, or 2) something in mox)

Good to hear. You could try connecting to the port "manually". For example:

> $ nc -v mail.axillis.nl 465
> Connection to mail.axillis.nl (84.22.96.237) 465 port [tcp/submissions] succeeded!

If that is failing (timeout or connection refused), then it's probably a firewall.

You can also try to set up a tls connection:

> openssl s_client -connect mail.axillis.nl:465
> [lots of tls-related output]
> 220 mail.axillis.nl ESMTP mox ...

If that results in a TLS error, or in final output that doesn't look like a "220" smtp response, that should give a hint for further investigation.

**Comment by mjl-** [comment]
for completeness, some more replies, even though you have solved it already.

> However, it seems like connections on port 465 from externals never arrive to that port: all the connection requests I can see in the log are on port 25 (from various other IPs), and successful connections to imaps port 993 from my IP

it's quite common to see bots trying to login on regular smtp port 25. it's never going to work with mox. and the bots don't even check if authentication is available on the port. also, mox has a rate limiter, so bots that scan too many accounts too quickly will be blocked for a while.

> - and finally, would it be possible, all of this is related to my other issue with reverse DNS mismatch? (possibly, imapserver able to listen on 993, but smtp server not listening on 465???)

no, i don't think the reported dns mismatch can have anything to do with being able to connect to that port.

> Otherwise, everything looks awesome: I get 9.5 score from mail-tester, and my trial mails to gmail arrived even under Priority :) ... all of these sent from webmail, of course

nice, good to hear!

**Comment by zkazsi** [comment]
> ok, then it's the actual reverse lookup that is giving back these results.

> Have you tried getting a shell in the container where mox is running and trying to do a reverse lookup? With commands host, dig or nslookup. Example:
> […](#)
> $ host 1.1.1.1 1.1.1.1.in-addr.arpa domain name pointer one.one.one.one.

Of the three commands only nslookup works in the container shell - however, the issue remains. See below:
```
~/docker/mox-mail$ docker compose run mox sh
/mox # nslookup 45.9z.x.y
Server:		8.8.8.8
Address:	8.8.8.8:53

Non-authoritative answer:
y.x.9z.45.in-addr.arpa	name = mail.owndomain.example

/mox # nslookup mail.owndomain.example
Server:		8.8.8.8
Address:	8.8.8.8:53

Non-authoritative answer:

Non-authoritative answer:
Name:	mail.owndomain.example
Address: 45.9z.x.y
```
So, as you see, even within the container, it seems , the reverse dns is identified correctly. Only on the DNS check page not...

One more thing, even though I don't think it has to do with it: in the config file, "Listeners" section "internal" I have these IPs:
```
        internal:
                IPs:
                        - 172.17.0.1
                        - 127.0.0.1
```
I've tried and copied 172.17.0.1 (the docker IP) to NATIPs, and it didnt't help (only caused all kind of additional errors on the DNS check page) - so , removed quickly, and even deactivated NATIPs for now fully

BTW, I am still very thankful for your patience :) , and insightful explanations. I tried also the other tools (nc and openssl s_client), and all works as expected. I'm learning something new from each message :)

**Comment by mjl-** [comment]
> So, as you see, even within the container, it seems , the reverse dns is identified correctly. Only on the DNS check page not...

ah clear. than i have one final likely candidate cause: /etc/hosts (inside the container).
i suspect your public ip is in there without the full/correct host name. if you modify it, hopefully the warning will go away.
nslookup only does dns lookups. mox does a lookup through the resolver that also checks /etc/hosts.
this makes me realize i probably want to change dns lookups in mox to query external dns before /etc/hosts.

> BTW, I am still very thankful for your patience :) , and insightful explanations. I tried also the other tools (nc and openssl s_client), and all works as expected. I'm learning something new from each message :)

nice to hear, happy to help. (:

**Comment by zkazsi** [comment]
And we have a solution!!! THANK YOU!

Indeed, in the /etc/hosts file the racknerd-xxxx was listed with the external IP (this was on the host, and also linked in the container): changed it on the host to mail.owndomain.example and now everything is great

It was quite a process, but I enjoyed every minute of it :)

I'm closing the issue. Once again, I appreciate all your help!
BTW, did you think about activating "Discussions" on github? (I think my issue might have been more like a discussion, and as mox grows, maybe more discussion-type topics happen)

**Comment by mjl-** [comment]
Glad it worked out!
I want to think about having a place for discussions. Not sure if github discussions is the right thing. I don't want to be too locked into github... External forum, or mailing list, would also make sense. For now the issues work for me, but it may be a hurdle for others to open an issue when it would feel like a discussion would be better...
