### ISSUE TITLE
dns name has trailing dot" pkg=mox domain=

### ISSUE THREAD

**Issue by adonese** [mjl-/mox#75]
I'm getting this error, i searched the code and it seems to be here:
https://github.com/mjl-/mox/blob/c4324fdaa1309ded196ba6d22fee7df8624ddfa2/mox-/config.go#L250-L251

Tried to rg through mox/config but without much success either

**Comment by mjl-** [comment]
> I'm getting this error, i searched the code and it seems to be here:
> https://github.com/mjl-/mox/blob/c4324fdaa1309ded196ba6d22fee7df8624ddfa2/mox-/config.go#L250-L251
> 
> Tried to rg through mox/config but without much success either

Thanks for the report. I think I may have found a way to reproduce the issue. But perhaps it's different from your situation. I can reproduce it by adding a domain name with a trailing dot to the Domains in config/domains.conf:

```
Domains:
        mox.example.:
                ...
```

When parsing the config file, we arrive at https://github.com/mjl-/mox/blob/c4324fdaa1309ded196ba6d22fee7df8624ddfa2/mox-/config.go#L895.
It gets an error and adds it to the error list, but continues but with an empty domain, i.e. ASCII/Unicode both empty strings.
After the errors, we try to set the allowed hosts for ACME, through https://github.com/mjl-/mox/blob/c4324fdaa1309ded196ba6d22fee7df8624ddfa2/mox-/config.go#L423.
And then dom.Domain.ASCII is empty at https://github.com/mjl-/mox/blob/c4324fdaa1309ded196ba6d22fee7df8624ddfa2/mox-/config.go#L249, causing the string to be "autoconfig.", which has a trailing dot, which isn't allowed. Mox is strict with its dns name handling to prevent confusion in the code (i.e. ascii vs unicode is strict, and relative vs absolute names (trailing dot)).

However, when I try to start mox with this configuration, I'm also getting a final fatal error that describes the issue:

```
l=error m="parsing autoconfig domain" err="dns name has trailing dot" pkg=mox domain=
l=error m="parsing mta-sts domain" err="dns name has trailing dot" pkg=mox domain=
l=debug m="autotls setting allowed hostnames" pkg=autotls hostnames=[...] publicips=[...]
l=fatal m="loading config file" err="bad domain \"mox.example.\": dns name has trailing dot" pkg=mox
```

And I'm guessing you aren't seeing that final fatal error. When is this error message happening for you? Perhaps when reloading the config? Do you also have a domain with a trailing dot in the domain? Perhaps you added it through the admin web interface?

**Comment by adonese** [comment]
Hi @mjl- and thanks a lot for the thorough explanation, it really helps a lot. I will mark this as closed.

I'm currently evaluating mox for a non-profit org, so I might be making some issues AND hopefully contribute as well

**Comment by lormayna** [comment]
Same error here:

```
Feb 09 07:57:27 localhost systemd[1]: Started mox.service - mox mail server.
Feb 09 07:57:27 localhost mox[96056]: l=error m="parsing autoconfig domain" err="dns name has trailing dot" pkg=mox domain=
Feb 09 07:57:27 localhost mox[96056]: l=error m="parsing mta-sts domain" err="dns name has trailing dot" pkg=mox domain=
Feb 09 07:57:27 localhost mox[96056]: l=debug m="autotls setting allowed hostnames" pkg=mox hostnames=[;mail.mydomain.tld] publicips=[$IPv4,$IPv6]
Feb 09 07:57:27 localhost mox[96056]: l=fatal m="loading config file" err="parsing dynamic config file: :41: expected indent" pkg=mox
Feb 09 07:57:27 localhost systemd[1]: mox.service: Main process exited, code=exited, status=1/FAILURE
```
It seems that the trailing dot is added automatically by the domain registrar. 

```
root@localhost:/home/mox# dig mta-sts.mydomain.tld +short
mail.mydomain.tld.
$IPv4
```

**Comment by mjl-** [comment]
> Feb 09 07:57:27 localhost mox[96056]: l=fatal m="loading config file" err="parsing dynamic config file: :41: expected indent" pkg=mox

i think that is the actual problem. i suspect there are spaces instead of tabs on line 41 of domains.conf.

this error:

> Feb 09 07:57:27 localhost mox[96056]: l=error m="parsing autoconfig domain" err="dns name has trailing dot" pkg=mox domain=

is a result of the config file not being parsed properly.
i see how this is confusing, given it comes before the actual error message.

**Comment by lormayna** [comment]
I just checked it, but it seems no spaces there.
I also try to convert space to tabs with unexpand, but no luck:

```
root@localhost:/home/mox/config# unexpand domains.conf > domains.conf.new
root@localhost:/home/mox/config# diff domains.conf domains.conf.new
root@localhost:/home/mox/config#
```

**Comment by mjl-** [comment]
then it is probably another snippet of text that has an unexpected indent.
i suppose `mox config test` also returns an error?
seeing the text around line 41 would help, feel free to send it to me directly (mechiel@ueber.net) if you don't want it public.
