### ISSUE TITLE
Try reloading TLS certs before erroring

### ISSUE THREAD

**Issue by mattfbacon** [mjl-/mox#77]
If there is some external tool renewing the TLS certificates, the mail server may retain the old certificates. As such, if the TLS certificate expires and mox notices this, I would like it to check if there is a new TLS certificate and, if there is, reload it.

This may be problematic with the current "start as root, load certs, drop perms" model of launching, but I would be fine with it just trying to load the certs as its normal unprivileged user; I can handle setting up the permissions properly.

**Comment by mjl-** [comment]
Ah, I suppose this is the reason for issue #76 as well?
Indeed, currently the only approach is to restart mox after getting a new certificate. I can see why that doesn't feel great. Perhaps we could add a command to only reload the statically configured TLS keys/certs from mox.conf. I'll have a look. Or if you would like to try implementing it, that would be good too of course. (:

**Comment by mattfbacon** [comment]
I guess the question would be, how does mox reload the certs when it handles the letsencrypt renewal internally?

**Comment by mattfbacon** [comment]
Yeah, similar to that, but my idea was just to check the expiration inside the TLS cert and reload it from the same path once before failing. Not so complicated as continually checking the certs for updates.

Btw, the use case for me was with certbot running separately. In my installation, I just put an ExecStartPost in the certbot systemd unit to reload-or-restart everything that depends on the certs (currently nginx and mox).

**Comment by mattfbacon** [comment]
Closing this because the restarting approach works fine.

**Comment by mjl-** [comment]
I wouldn't mind leaving this open. I think mox can be changed to just try to reload the certificate while it is running. When permissions are such that mox can read the key file, and they contain a modified and valid key, the file can be reloaded. When there is no permission (during first attempt to load it after starting), mox can just not try reloading the file. It's not high on the priority list though...

**Comment by mattfbacon** [comment]
Sure, I'm just saying that I am no longer interested in implementing this.
