### ISSUE TITLE
Webmail + nginx = upstream timed out

### ISSUE THREAD

**Issue by mattfbacon** [mjl-/mox#78]
(This is a Q&A style issue where I already have the answer.)

When trying to access webmail it just gets stuck here, with the actual content just stuck at "loading...":

![Stuck on "loading..."](https://github.com/mjl-/mox/assets/58113890/2002ae8a-c884-4f47-967e-11dfee34f326)

And I see this in my nginx log:

```
2023/10/11 07:35:38 [error] 28612#28612: *377 upstream timed out (110: Connection timed out) while reading upstream, client: REDACTED, server: mail.domain.name, request: "GET /webmail/events?token=REDACTED&request=%7B%22ID%22%3A1%2C%22ViewID%22%3A1%2C%22Query%22%3A%7B%22OrderAsc%22%3Afalse%2C%22Threading%22%3A%22on%22%2C%22Filter%22%3A%7B%22MailboxID%22%3A0%2C%22MailboxChildrenIncluded%22%3Afalse%2C%22MailboxName%22%3A%22Inbox%22%2C%22Attachments%22%3A%22%22%2C%22SizeMin%22%3A0%2C%22SizeMax%22%3A0%7D%2C%22NotFilter%22%3A%7B%22Attachments%22%3A%22%22%7D%7D%2C%22Page%22%3A%7B%22AnchorMessageID%22%3A0%2C%22Count%22%3A117%2C%22DestMessageID%22%3A0%7D%7D HTTP/2.0", upstream: "http://127.0.0.1:1080/webmail/events?token=REDACTED&request=%7B%22ID%22%3A1%2C%22ViewID%22%3A1%2C%22Query%22%3A%7B%22OrderAsc%22%3Afalse%2C%22Threading%22%3A%22on%22%2C%22Filter%22%3A%7B%22MailboxID%22%3A0%2C%22MailboxChildrenIncluded%22%3Afalse%2C%22MailboxName%22%3A%22Inbox%22%2C%22Attachments%22%3A%22%22%2C%22SizeMin%22%3A0%2C%22SizeMax%22%3A0%7D%2C%22NotFilter%22%3A%7B%22Attachments%22%3A%22%22%7D%7D%2C%22Page%22%3A%7B%22AnchorMessageID%22%3A0%2C%22Count%22%3A117%2C%22DestMessageID%22%3A0%7D%7D", host: "mail.domain.name", referrer: "https://mail.domain.name/webmail/"
```

**Comment by mattfbacon** [comment]
However, I think the canonical solution here is setting the X-Accel-Buffering header to "no". Not sure if @mjl- would be interested in adding this, because it is a bit biased toward a specific setup (running behind nginx as a reverse proxy).

**Comment by mjl-** [comment]
I don't mind adding the header for the SSE endpoints (there is one for status updates for mbox/maildir updates through the account web interface too). But I would only add it for requests that were actually reverse proxied.

Unfortunately, it doesn't look like nginx sets X-Forwarded-* headers by default, or any other header that indicates it is a forwarded requests (not sure why, it seems like the reasonable default to me). There is an nginx proxy_params file that is supposed to help, but has to be included explicitly by the admin configuring nginx. I suppose that is somewhat common to do, but those in the know may already know about the need to disable buffering too. @mattfbacon did you have (the equivalent of) proxy_params that set X-Forwarded-* headers when you ran into this issue? If so, we could add "X-Accel-Buffering: no" to responses in case a X-Forwarded-For header is present.

I can imagine nginx wants to gather (buffer) most types of requests/responses, for  handling conditional requests, or serving a compressed version from the cache. But a better default for nginx would be disable it for SSE responses. It's not like SSE is a new concept, and it is easy to detect.

**Comment by mattfbacon** [comment]
> did you have (the equivalent of) proxy_params that set X-Forwarded-* headers

I'm not sure. I didn't add any proxy params to my config beyond the ones outlined in the issue, so unless nginx adds that automatically, I don't have it.

**Comment by ptman** [comment]
The magic config line that makes it work is

    proxy_buffering off;

as per #195
