### ISSUE TITLE
Webmail top-posting

### ISSUE THREAD

**Issue by mattfbacon** [mjl-/mox#83]
Ignoring all the quasi-religious arguments about top- vs bottom-posting, I'd like an option in the webmail for top-posting.

**Comment by mjl-** [comment]
> Ignoring all the quasi-religious arguments about top- vs bottom-posting, I'd like an option in the webmail for top-posting.

what about this: if you select text in the original message and hit reply, you get bottom-posting (like currently).
if you don't select text and hit reply, you start out with top-posting, i.e. empty line and cursor at the top.
or do you have something else in mind with facilitating top-posting?

**Comment by mattfbacon** [comment]
If that wouldn't be too onerous for the bottom-posters, absolutely :)

**Comment by mattfbacon** [comment]
In that case, we may also need to have the "On Friday, 1 Jan, 11:37, John Doe wrote:" thing.

**Comment by mjl-** [comment]
> In that case, we may also need to have the "On Friday, 1 Jan, 11:37, John Doe wrote:" thing.

i suppose so. (:
best to make it a setting. i would want it off by default, at least for bottom-posting. and when starting on settings, making the "on ... wrote:"-line configurable lets users specify it in their language.

mox webmail doesn't have a way to store settings on the server yet. i may give that some thought before adding the "on ...wrote"-line. but the top vs bottom posting can be done without setting. i'll get to that in a few hours. i'll also try implementing missing utf-8 attachment filenames.

**Comment by mattfbacon** [comment]
> lets users specify it in their language.

Definitely. I'd love if this could be fully customizable with format specifiers for the time, the username and email of the sender, etc.

> mox webmail doesn't have a way to store settings on the server yet.

Yeah, I noticed this. It would add complexity, I guess, but it will probably be useful in the future because some things are kind of imitating configuration currently, like the threads toggle. If that could be an actual config option that persists between sessions, it would probably improve UX.

> but the top vs bottom posting can be done without setting. i'll get to that in a few hours. i'll also try implementing missing utf-8 attachment filenames.

Thanks. I looked into doing this myself for both but I'm not familiar with the structure of the code. I'll definitely read your commits to learn more about it.

**Comment by mattfbacon** [comment]
OK, thanks for that commit. It was simpler than I thought 🙂

**Comment by mjl-** [comment]
yeah, this was relatively easy to bolt on. the ui code doesn't have tests (so it sometimes feels like hacking in functionality, though ui tests are hard to make useful and non-brittle). at least typescripts helps with maintainability. but it's indeed somewhat surprising how easy some changes/features are to implement. (:

**Comment by mattfbacon** [comment]
Closing this because the initial issue is resolved and server-side config is a separate thing. BTW, was the UTF-8 attachment names thing fixed?
