### ISSUE TITLE
Postmaster email

### ISSUE THREAD

**Issue by mattfbacon** [mjl-/mox#87]
I'm concerned about this line:

https://github.com/mjl-/mox/blob/8a866a60dcba1e9e008f177eca076371d06a015f/queue/dsn.go#L104

I have received some DSNs from this address and I don't like it because it's not a real address that the mail server serves. I would prefer if it used the email address of the configured `Postmaster.Account`.

**Comment by mjl-** [comment]
config.Static.Postmaster configures an account and mailbox, but not an email address. 
Delivering to postmaster@host should work though, through the special postmaster-handling at https://github.com/mjl-/mox/blob/8a866a60dcba1e9e008f177eca076371d06a015f/mox-/lookup.go#L39 (for the mail server hostname) and https://github.com/mjl-/mox/blob/8a866a60dcba1e9e008f177eca076371d06a015f/mox-/lookup.go#L60 (for each domain).

The smtp server can send a DSN with a postmaster@domain "from" address, see https://github.com/mjl-/mox/blob/8a866a60dcba1e9e008f177eca076371d06a015f/smtpserver/server.go#L2570

So the postmaster addresses don't have to be configured explicitly. The logic in mox-/lookup.go lets you override a per-domain postmaster address (and the wildcard address matches too). The per-host postmaster address cannot be overridden by a regular email address configuration, but can only be configured through mox.conf.

**Comment by mattfbacon** [comment]
OK, but if the postmaster account has an associated email address, shouldn't that email be used instead of the synthesized postmaster address?

Also, I am concerned in part because the hostname is wrong: my server's hostname is "vps2.felle.nz" but my email address uses "felle.nz" as the host.

**Comment by mjl-** [comment]
In my instances, the postmaster account is my own account, which has many addresses. There wouldn't be a single address to choose, they aren't ordered...

In your case I expect mox.Conf.Static.HostnameDomain to be vps2.felle.nz and that messages to both postmaster@vps2.felle.nz and postmaster@felle.nz will be delivered to your postmaster's account. You could give it a try to be sure.

I thought adding more documentation to the Postmaster config option in config/config.go may helpt, but it seems to already have some text about the postmaster addresses. Perhaps it should mention explicitly that the postmaster addresses aren't explicitly configured and that DSNs can be sent from the postmaster@host and all postmaster@domain addresses? Or perhaps it can be mentioned in another place where you might look for this information?

**Comment by mattfbacon** [comment]
That makes sense, it was just confusing to me where the postmaster@vps2.felle.nz address came from

**Comment by mattfbacon** [comment]
Closing since the current behavior is acceptable as clarified in this issue
