### ISSUE TITLE
websites on 443 + mox

### ISSUE THREAD

**Issue by zigomi** [mjl-/mox#92]
There're multiple websites on a VPS, with nginx as a reverse proxy, on 443 port.

How to properly set up  mox with this? 

Using the built-in webserver of mox isn't an option at all.

**Comment by naturalethic** [comment]
From the docs:

> You can run mox along with an existing webserver, but because of MTA-STS and autoconfig, you'll need to forward HTTPS traffic for two domains to mox. Run "mox quickstart -existing-webserver ..." to generate configuration files and instructions for configuring mox along with an existing webserver.
