### ISSUE TITLE
How to expose the web server onto the internet?

### ISSUE THREAD

**Issue by zigomi** [mjl-/mox#93]
Instead of having running

```
ssh -L 8080:localhost:80  root@11.22.33.44
```

how to expose the built-in server onto the internet? Does mox support it or will I have to run nginx as reverse proxy?

Also, what's the root route  `http://localhost/` for? There're `http://localhost/admin` and `http://localhost/webmail` for which mox generates the credentials. But for the root path - not.

**Comment by mjl-** [comment]
There are various options:

- If you have a VPN into the machine, make the internal listener bind to the (internal) VPN IP. This is what I personally use. But it's not the easiest if you don't already have a VPN into your machine.
- Expose the admin/account/webmail functionality on the public listener, making it available on the public IP. You would have to modify config/mox.conf, move/copy some of the {Webmail,Admin,Account}HTTP(S) settings from the internal listener to the public listener.
- If you have a different webserver, like nginx, you could configure a forwarding rule from an external URL to the localhost URLs.

The route http://localhost/ is for the "account" page. Where a user/account can import/export messages, change their display name, change rules for delivering incoming messages into certain mailboxes, etc. I plan to merge the account page into the webmail (but there are things higher up on the todo list). The account endpoint is configured through AccountHTTP(S) in a Listener in config/mox.conf. See this snippet:

> # Account web interface, for email users wanting to change their accounts, e.g.
> # set new password, set new delivery rulesets. Served at /. (optional)
> AccountHTTP:
> 	Enabled: true

**Comment by zigomi** [comment]
>- Expose the admin/account/webmail functionality on the public listener, making it available on the public IP. You would have to modify config/mox.conf, move/copy some of the {Webmail,Admin,Account}HTTP(S) settings from the internal listener to the public listener.

It'll be http only, right? Apart from `nginx` as a reverse proxy, the 3rd option, can mox make it https on its own?

>The route http://localhost/ is for the "account" page. Where a user/account can import/export messages, change their display name, change rules for delivering incoming messages into certain mailboxes, etc. 

Ok, but  neither the admin, nor the mailaccount credentials work on it. Or should it be ignored, since you'll be merging it?

**Comment by mjl-** [comment]
> It'll be http only, right? Apart from nginx as a reverse proxy, the 3rd option, can mox make it https on its own? Namely, with existings https websites on the same server.

For the Admin, Account and Webmail interfaces, you can enable HTTPS as well. Instead of AccountHTTP, use AccountHTTPS, and likewise use AdminHTTPS and WebmailHTTPS. That should expose those services on HTTPS.

> Ok, but neither the admin, nor the mailaccount credentials work on it. Or should it be ignored, since you'll be merging it?

Oh, that is surprising. The account password should work. Are you logging in with an email address + password? Logging in with the account name as username won't work. That's still somewhat misleading, though the authentication-failed error message does mention that you need to use the email address of the account (or are you not getting that error message? e.g. if you hit escape in the HTTP password popup).

**Comment by zigomi** [comment]
All good now.

**Comment by mave-git** [comment]
Hi mjl,

these are not my first steps on servers, but I don't understand your mox.conf with listeners and XY. Maybe you could give an config-example with nginx or caddy-webserver to explain what is do to exposing mox-sites? It's definitly no way reaching users e.g. the account-page saying: "Go with ssh -L 8080 ..." and give passwords of the mox-server.

First I meant - like zigomi - searching endpoints (e.g. for caddy), but this doesn't work.

Regards,
Markus

**Comment by mjl-** [comment]
@mave-git Hopefully you've find a solution in the mean time. The easiest solution is probably to enable the webmail and account pages on the https webserver on the public listener (the quickstart enables it on the "internal" listener on plain http only). That would amount to this snippet in mox.conf:

```
Listeners:
	internal:
		[...]
	public:
		[...]

                AccountHTTPS:
                        Enabled: true

                WebmailHTTPS:
                        Enabled: true
```

After restarting, the account & webmail pages should be available for all users at your public mail hostname, e.g. account pages at `https://mail.yourdomain.example/`, and the webmail at `https://mail.yourdomain.example/webmail/`.
