### ISSUE TITLE
Collapse address lists (To, From, etc)

### ISSUE THREAD

**Issue by mattfbacon** [mjl-/mox#98]
Sometimes I get emails with a lot of recipients. This causes awkwardness in the current UI. It would be nice to collapse the list to show maybe two or three entries and a button to expand to the full list. Or just show the shortened list unless the "full header" mode (Ctrl-shift-i) is activated.

**Comment by mjl-** [comment]
Thanks, sounds useful, I've run into it a few times as well. I'll give implementing it a try.

**Comment by mjl-** [comment]
I think this has been resolved now, so closing the issue. Feel free to reopen if needed.
